// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Possible states of a car in regards to ground contact and jump/dodging forces.
 * See more about jumping physics at https://wiki.rlbot.org/botmaking/jumping-physics/
 */
export enum AirState {
  /**
   * All wheels are on the ground and the car is affected by wall-stickiness forces.
   */
  OnGround = 0,

  /**
   * The car is currently affected by jumping forces of an initial jump.
   * Lasts until the player lets go of jump button but at most for 0.2 seconds (240 ticks).
   * The following AirState is typically InAir.
   */
  Jumping = 1,

  /**
   * The car is currently affected by jumping forces of a secondary jump (just an impulse in practice).
   * Lasts for 13 ticks.
   * The following AirState is typically InAir.
   */
  DoubleJumping = 2,

  /**
   * The car is currently affected by forces and torque of a dodges.
   * This lasts for 79 ticks.
   * The following AirState is typically InAir.
   */
  Dodging = 3,

  /**
   * The car is free falling.
   */
  InAir = 4
}
