// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BoxShape, BoxShapeT } from '../../flat/flat/box-shape.js';
import { CollisionShape, unionToCollisionShape, unionListToCollisionShape } from '../../flat/flat/collision-shape.js';
import { CylinderShape, CylinderShapeT } from '../../flat/flat/cylinder-shape.js';
import { Physics, PhysicsT } from '../../flat/flat/physics.js';
import { SphereShape, SphereShapeT } from '../../flat/flat/sphere-shape.js';


/**
 * Information about a ball.
 */
export class BallInfo implements flatbuffers.IUnpackableObject<BallInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BallInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBallInfo(bb:flatbuffers.ByteBuffer, obj?:BallInfo):BallInfo {
  return (obj || new BallInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBallInfo(bb:flatbuffers.ByteBuffer, obj?:BallInfo):BallInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BallInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The physical state of the ball.
 */
physics(obj?:Physics):Physics|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Physics()).__init(this.bb_pos + offset, this.bb!) : null;
}

shapeType():CollisionShape {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CollisionShape.NONE;
}

/**
 * The collision shape of the ball.
 */
shape<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startBallInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPhysics(builder:flatbuffers.Builder, physicsOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, physicsOffset, 0);
}

static addShapeType(builder:flatbuffers.Builder, shapeType:CollisionShape) {
  builder.addFieldInt8(1, shapeType, CollisionShape.NONE);
}

static addShape(builder:flatbuffers.Builder, shapeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, shapeOffset, 0);
}

static endBallInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // physics
  builder.requiredField(offset, 8) // shape
  return offset;
}

static createBallInfo(builder:flatbuffers.Builder, physicsOffset:flatbuffers.Offset, shapeType:CollisionShape, shapeOffset:flatbuffers.Offset):flatbuffers.Offset {
  BallInfo.startBallInfo(builder);
  BallInfo.addPhysics(builder, physicsOffset);
  BallInfo.addShapeType(builder, shapeType);
  BallInfo.addShape(builder, shapeOffset);
  return BallInfo.endBallInfo(builder);
}

unpack(): BallInfoT {
  return new BallInfoT(
    (this.physics() !== null ? this.physics()!.unpack() : null),
    this.shapeType(),
    (() => {
      const temp = unionToCollisionShape(this.shapeType(), this.shape.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: BallInfoT): void {
  _o.physics = (this.physics() !== null ? this.physics()!.unpack() : null);
  _o.shapeType = this.shapeType();
  _o.shape = (() => {
      const temp = unionToCollisionShape(this.shapeType(), this.shape.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class BallInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public physics: PhysicsT|null = null,
  public shapeType: CollisionShape = CollisionShape.NONE,
  public shape: BoxShapeT|CylinderShapeT|SphereShapeT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const shape = builder.createObjectOffset(this.shape);

  return BallInfo.createBallInfo(builder,
    (this.physics !== null ? this.physics!.pack(builder) : 0),
    this.shapeType,
    shape
  );
}
}
