// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Ball max speed mutator options.
 */
export enum BallMaxSpeedMutator {
  Default = 0,
  Slow = 1,
  Fast = 2,
  SuperFast = 3
}
