// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Ball type mutator options.
 */
export enum BallTypeMutator {
  Default = 0,
  Cube = 1,
  Puck = 2,
  Basketball = 3,
  Beachball = 4,
  Anniversary = 5,
  Haunted = 6,
  Ekin = 7,
  SpookyCube = 8,
  Egg = 9,
  PlayerSeeking = 10,
  Dropshot = 11,
  ScoreAbsorb = 12,
  Shoe = 13,
  PizzaPuck = 14
}
