// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vector3, Vector3T } from '../../flat/flat/vector3.js';


/**
 * A RenderAnchor attached to a ball.
 * The local field allows for an offset in local coordinates taking the ball's orientation into account.
 */
export class BallAnchor implements flatbuffers.IUnpackableObject<BallAnchorT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BallAnchor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBallAnchor(bb:flatbuffers.ByteBuffer, obj?:BallAnchor):BallAnchor {
  return (obj || new BallAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBallAnchor(bb:flatbuffers.ByteBuffer, obj?:BallAnchor):BallAnchor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BallAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The index of the ball.
 */
index():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * An offset in local coordinates.
 * x is forwards, y is left, and z is up.
 */
local(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startBallAnchor(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
}

static addLocal(builder:flatbuffers.Builder, localOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, localOffset, 0);
}

static endBallAnchor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // local
  return offset;
}


unpack(): BallAnchorT {
  return new BallAnchorT(
    this.index(),
    (this.local() !== null ? this.local()!.unpack() : null)
  );
}


unpackTo(_o: BallAnchorT): void {
  _o.index = this.index();
  _o.local = (this.local() !== null ? this.local()!.unpack() : null);
}
}

export class BallAnchorT implements flatbuffers.IGeneratedObject {
constructor(
  public index: number = 0,
  public local: Vector3T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  BallAnchor.startBallAnchor(builder);
  BallAnchor.addIndex(builder, this.index);
  BallAnchor.addLocal(builder, (this.local !== null ? this.local!.pack(builder) : 0));

  return BallAnchor.endBallAnchor(builder);
}
}
