// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Ball size mutator options.
 */
export enum BallSizeMutator {
  Default = 0,
  Small = 1,
  Medium = 2,
  Large = 3,
  Gigantic = 4
}
