// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Ball weight mutator options.
 */
export enum BallWeightMutator {
  Default = 0,
  Light = 1,
  Heavy = 2,
  SuperLight = 3,
  CurveBall = 4,
  BeachBallCurve = 5,
  MagnusFutBall = 6,
  MagnusFutballLess = 7
}
