// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Boost strength mutator options.
 */
export enum BoostStrengthMutator {
  One = 0,
  OneAndAHalf = 1,
  Two = 2,
  Five = 3,
  Ten = 4
}
