// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Boost amount mutator options.
 */
export enum BoostAmountMutator {
  NormalBoost = 0,
  UnlimitedBoost = 1,
  SlowRecharge = 2,
  RapidRecharge = 3,
  NoBoost = 4
}
