// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * The state of a boost pad.
 * Note, static properties of boost pads, such as their location and size, are found in the field info.
 */
export class BoostPadState implements flatbuffers.IUnpackableObject<BoostPadStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BoostPadState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * True if the boost can be picked up right now.
 */
isActive():boolean {
  return !!this.bb!.readInt8(this.bb_pos);
}

/**
 * The number of seconds since the boost has been picked up, or 0 if the boost is active.
 * A big boost pad becomes active again after 10 seconds.
 * A small boost pad becomes active again after 4 seconds.
 */
timer():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createBoostPadState(builder:flatbuffers.Builder, is_active: boolean, timer: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(timer);
  builder.pad(3);
  builder.writeInt8(Number(Boolean(is_active)));
  return builder.offset();
}


unpack(): BoostPadStateT {
  return new BoostPadStateT(
    this.isActive(),
    this.timer()
  );
}


unpackTo(_o: BoostPadStateT): void {
  _o.isActive = this.isActive();
  _o.timer = this.timer();
}
}

export class BoostPadStateT implements flatbuffers.IGeneratedObject {
constructor(
  public isActive: boolean = false,
  public timer: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return BoostPadState.createBoostPadState(builder,
    this.isActive,
    this.timer
  );
}
}
