// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * An RGBA color.
 */
export class Color implements flatbuffers.IUnpackableObject<ColorT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Color {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

r():number {
  return this.bb!.readUint8(this.bb_pos);
}

g():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

b():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

a():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

static sizeOf():number {
  return 4;
}

static createColor(builder:flatbuffers.Builder, r: number, g: number, b: number, a: number):flatbuffers.Offset {
  builder.prep(1, 4);
  builder.writeInt8(a);
  builder.writeInt8(b);
  builder.writeInt8(g);
  builder.writeInt8(r);
  return builder.offset();
}


unpack(): ColorT {
  return new ColorT(
    this.r(),
    this.g(),
    this.b(),
    this.a()
  );
}


unpackTo(_o: ColorT): void {
  _o.r = this.r();
  _o.g = this.g();
  _o.b = this.b();
  _o.a = this.a();
}
}

export class ColorT implements flatbuffers.IGeneratedObject {
constructor(
  public r: number = 0,
  public g: number = 0,
  public b: number = 0,
  public a: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Color.createColor(builder,
    this.r,
    this.g,
    this.b,
    this.a
  );
}
}
