// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Sent by clients when connecting to RLBot to indicate what type of messages are desired.
 * This could be sent by a bot, or a bot manager governing several bots, an
 * overlay, or any other utility that connects to the RLBot process.
 */
export class ConnectionSettings implements flatbuffers.IUnpackableObject<ConnectionSettingsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConnectionSettings {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConnectionSettings(bb:flatbuffers.ByteBuffer, obj?:ConnectionSettings):ConnectionSettings {
  return (obj || new ConnectionSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConnectionSettings(bb:flatbuffers.ByteBuffer, obj?:ConnectionSettings):ConnectionSettings {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConnectionSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The ID of the bot/script that is associated with the incoming connection.
 */
agentId():string|null
agentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
agentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * If this is set, RLBot will send BallPrediction data back to the client when available.
 */
wantsBallPredictions():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * If this is set, RLBot will send MatchComms to the client when available.
 */
wantsComms():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * If this is set, RLBot will close the connection when a match is stopped or when a new
 * match is started. The GUI and other match runners should likely not set this.
 */
closeBetweenMatches():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startConnectionSettings(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAgentId(builder:flatbuffers.Builder, agentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, agentIdOffset, 0);
}

static addWantsBallPredictions(builder:flatbuffers.Builder, wantsBallPredictions:boolean) {
  builder.addFieldInt8(1, +wantsBallPredictions, +false);
}

static addWantsComms(builder:flatbuffers.Builder, wantsComms:boolean) {
  builder.addFieldInt8(2, +wantsComms, +false);
}

static addCloseBetweenMatches(builder:flatbuffers.Builder, closeBetweenMatches:boolean) {
  builder.addFieldInt8(3, +closeBetweenMatches, +false);
}

static endConnectionSettings(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // agent_id
  return offset;
}

static createConnectionSettings(builder:flatbuffers.Builder, agentIdOffset:flatbuffers.Offset, wantsBallPredictions:boolean, wantsComms:boolean, closeBetweenMatches:boolean):flatbuffers.Offset {
  ConnectionSettings.startConnectionSettings(builder);
  ConnectionSettings.addAgentId(builder, agentIdOffset);
  ConnectionSettings.addWantsBallPredictions(builder, wantsBallPredictions);
  ConnectionSettings.addWantsComms(builder, wantsComms);
  ConnectionSettings.addCloseBetweenMatches(builder, closeBetweenMatches);
  return ConnectionSettings.endConnectionSettings(builder);
}

unpack(): ConnectionSettingsT {
  return new ConnectionSettingsT(
    this.agentId(),
    this.wantsBallPredictions(),
    this.wantsComms(),
    this.closeBetweenMatches()
  );
}


unpackTo(_o: ConnectionSettingsT): void {
  _o.agentId = this.agentId();
  _o.wantsBallPredictions = this.wantsBallPredictions();
  _o.wantsComms = this.wantsComms();
  _o.closeBetweenMatches = this.closeBetweenMatches();
}
}

export class ConnectionSettingsT implements flatbuffers.IGeneratedObject {
constructor(
  public agentId: string|Uint8Array|null = null,
  public wantsBallPredictions: boolean = false,
  public wantsComms: boolean = false,
  public closeBetweenMatches: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const agentId = (this.agentId !== null ? builder.createString(this.agentId!) : 0);

  return ConnectionSettings.createConnectionSettings(builder,
    agentId,
    this.wantsBallPredictions,
    this.wantsComms,
    this.closeBetweenMatches
  );
}
}
