// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ControllableInfo, ControllableInfoT } from '../../flat/flat/controllable-info.js';


/**
 * Server message with information about the cars that the client can control.
 * Sent to bot clients as a response to ConnectionSettings.
 * There may be more than one car in case the bot is a hivemind.
 */
export class ControllableTeamInfo implements flatbuffers.IUnpackableObject<ControllableTeamInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ControllableTeamInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsControllableTeamInfo(bb:flatbuffers.ByteBuffer, obj?:ControllableTeamInfo):ControllableTeamInfo {
  return (obj || new ControllableTeamInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsControllableTeamInfo(bb:flatbuffers.ByteBuffer, obj?:ControllableTeamInfo):ControllableTeamInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ControllableTeamInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The assigned team for this client.
 */
team():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The bots that RLBot will allow this client to control.
 */
controllables(index: number, obj?:ControllableInfo):ControllableInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ControllableInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

controllablesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startControllableTeamInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt32(0, team, 0);
}

static addControllables(builder:flatbuffers.Builder, controllablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, controllablesOffset, 0);
}

static createControllablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startControllablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endControllableTeamInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // controllables
  return offset;
}

static createControllableTeamInfo(builder:flatbuffers.Builder, team:number, controllablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ControllableTeamInfo.startControllableTeamInfo(builder);
  ControllableTeamInfo.addTeam(builder, team);
  ControllableTeamInfo.addControllables(builder, controllablesOffset);
  return ControllableTeamInfo.endControllableTeamInfo(builder);
}

unpack(): ControllableTeamInfoT {
  return new ControllableTeamInfoT(
    this.team(),
    this.bb!.createObjList<ControllableInfo, ControllableInfoT>(this.controllables.bind(this), this.controllablesLength())
  );
}


unpackTo(_o: ControllableTeamInfoT): void {
  _o.team = this.team();
  _o.controllables = this.bb!.createObjList<ControllableInfo, ControllableInfoT>(this.controllables.bind(this), this.controllablesLength());
}
}

export class ControllableTeamInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public team: number = 0,
  public controllables: (ControllableInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const controllables = ControllableTeamInfo.createControllablesVector(builder, builder.createObjectOffsetList(this.controllables));

  return ControllableTeamInfo.createControllableTeamInfo(builder,
    this.team,
    controllables
  );
}
}
