// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Information about a car that the client can control.
 */
export class ControllableInfo implements flatbuffers.IUnpackableObject<ControllableInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ControllableInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsControllableInfo(bb:flatbuffers.ByteBuffer, obj?:ControllableInfo):ControllableInfo {
  return (obj || new ControllableInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsControllableInfo(bb:flatbuffers.ByteBuffer, obj?:ControllableInfo):ControllableInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ControllableInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The index of the bot/script.
 */
index():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The id of the bot/script.
 * This value is mostly used internally to keep track of participants in the match.
 * The id can be used to find the corresponding PlayerConfiguration in the MatchConfiguration.
 */
identifier():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startControllableInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
}

static addIdentifier(builder:flatbuffers.Builder, identifier:number) {
  builder.addFieldInt32(1, identifier, 0);
}

static endControllableInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createControllableInfo(builder:flatbuffers.Builder, index:number, identifier:number):flatbuffers.Offset {
  ControllableInfo.startControllableInfo(builder);
  ControllableInfo.addIndex(builder, index);
  ControllableInfo.addIdentifier(builder, identifier);
  return ControllableInfo.endControllableInfo(builder);
}

unpack(): ControllableInfoT {
  return new ControllableInfoT(
    this.index(),
    this.identifier()
  );
}


unpackTo(_o: ControllableInfoT): void {
  _o.index = this.index();
  _o.identifier = this.identifier();
}
}

export class ControllableInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public index: number = 0,
  public identifier: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ControllableInfo.createControllableInfo(builder,
    this.index,
    this.identifier
  );
}
}
