// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BallPrediction, BallPredictionT } from '../../flat/flat/ball-prediction.js';
import { ControllableTeamInfo, ControllableTeamInfoT } from '../../flat/flat/controllable-team-info.js';
import { CoreMessage, unionToCoreMessage, unionListToCoreMessage } from '../../flat/flat/core-message.js';
import { DisconnectSignal, DisconnectSignalT } from '../../flat/flat/disconnect-signal.js';
import { FieldInfo, FieldInfoT } from '../../flat/flat/field-info.js';
import { GamePacket, GamePacketT } from '../../flat/flat/game-packet.js';
import { MatchComm, MatchCommT } from '../../flat/flat/match-comm.js';
import { MatchConfiguration, MatchConfigurationT } from '../../flat/flat/match-configuration.js';
import { PingRequest, PingRequestT } from '../../flat/flat/ping-request.js';
import { PingResponse, PingResponseT } from '../../flat/flat/ping-response.js';
import { RenderingStatus, RenderingStatusT } from '../../flat/flat/rendering-status.js';


/**
 * Packet containing a CoreMessage
 */
export class CorePacket implements flatbuffers.IUnpackableObject<CorePacketT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CorePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCorePacket(bb:flatbuffers.ByteBuffer, obj?:CorePacket):CorePacket {
  return (obj || new CorePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCorePacket(bb:flatbuffers.ByteBuffer, obj?:CorePacket):CorePacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CorePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageType():CoreMessage {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CoreMessage.NONE;
}

message<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startCorePacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessageType(builder:flatbuffers.Builder, messageType:CoreMessage) {
  builder.addFieldInt8(0, messageType, CoreMessage.NONE);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endCorePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // message
  return offset;
}

static createCorePacket(builder:flatbuffers.Builder, messageType:CoreMessage, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  CorePacket.startCorePacket(builder);
  CorePacket.addMessageType(builder, messageType);
  CorePacket.addMessage(builder, messageOffset);
  return CorePacket.endCorePacket(builder);
}

unpack(): CorePacketT {
  return new CorePacketT(
    this.messageType(),
    (() => {
      const temp = unionToCoreMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: CorePacketT): void {
  _o.messageType = this.messageType();
  _o.message = (() => {
      const temp = unionToCoreMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class CorePacketT implements flatbuffers.IGeneratedObject {
constructor(
  public messageType: CoreMessage = CoreMessage.NONE,
  public message: BallPredictionT|ControllableTeamInfoT|DisconnectSignalT|FieldInfoT|GamePacketT|MatchCommT|MatchConfigurationT|PingRequestT|PingResponseT|RenderingStatusT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = builder.createObjectOffset(this.message);

  return CorePacket.createCorePacket(builder,
    this.messageType,
    message
  );
}
}
