// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerLoadout, PlayerLoadoutT } from '../../flat/flat/player-loadout.js';


/**
 * A bot controlled by the RLBot framework.
 */
export class CustomBot implements flatbuffers.IUnpackableObject<CustomBotT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CustomBot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCustomBot(bb:flatbuffers.ByteBuffer, obj?:CustomBot):CustomBot {
  return (obj || new CustomBot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCustomBot(bb:flatbuffers.ByteBuffer, obj?:CustomBot):CustomBot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CustomBot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Requested bot name. When match start, RLBot will ensure each bot has a unique name; bots with
 * duplicate names will be renamed with a suffix like `(2)`
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The root directory of the bot and the working directory for the run command.
 */
rootDir():string|null
rootDir(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rootDir(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The console command that starts this bot.
 */
runCommand():string|null
runCommand(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
runCommand(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The loadout of the player.
 */
loadout(obj?:PlayerLoadout):PlayerLoadout|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PlayerLoadout()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * A unique user-defined string that is used to connect clients to the right players/scripts.
 * If a bot/script has a run command, RLBot will pass this agent id to the process using an environment variable, RLBOT_AGENT_ID.
 * Upon connecting the process announces that it is responsible for this agent id and RLBot will pair the two.
 * The recommended format for agent ids is "developer_name/bot_name".
 */
agentId():string|null
agentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
agentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Whether this player is part of a hivemind bot where all players/cars are controlled by the same process.
 * Players in the hivemind must have the same name, team, run command, and agent id.
 */
hivemind():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startCustomBot(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addRootDir(builder:flatbuffers.Builder, rootDirOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rootDirOffset, 0);
}

static addRunCommand(builder:flatbuffers.Builder, runCommandOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, runCommandOffset, 0);
}

static addLoadout(builder:flatbuffers.Builder, loadoutOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, loadoutOffset, 0);
}

static addAgentId(builder:flatbuffers.Builder, agentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, agentIdOffset, 0);
}

static addHivemind(builder:flatbuffers.Builder, hivemind:boolean) {
  builder.addFieldInt8(5, +hivemind, +false);
}

static endCustomBot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  builder.requiredField(offset, 6) // root_dir
  builder.requiredField(offset, 8) // run_command
  builder.requiredField(offset, 12) // agent_id
  return offset;
}


unpack(): CustomBotT {
  return new CustomBotT(
    this.name(),
    this.rootDir(),
    this.runCommand(),
    (this.loadout() !== null ? this.loadout()!.unpack() : null),
    this.agentId(),
    this.hivemind()
  );
}


unpackTo(_o: CustomBotT): void {
  _o.name = this.name();
  _o.rootDir = this.rootDir();
  _o.runCommand = this.runCommand();
  _o.loadout = (this.loadout() !== null ? this.loadout()!.unpack() : null);
  _o.agentId = this.agentId();
  _o.hivemind = this.hivemind();
}
}

export class CustomBotT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public rootDir: string|Uint8Array|null = null,
  public runCommand: string|Uint8Array|null = null,
  public loadout: PlayerLoadoutT|null = null,
  public agentId: string|Uint8Array|null = null,
  public hivemind: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const rootDir = (this.rootDir !== null ? builder.createString(this.rootDir!) : 0);
  const runCommand = (this.runCommand !== null ? builder.createString(this.runCommand!) : 0);
  const loadout = (this.loadout !== null ? this.loadout!.pack(builder) : 0);
  const agentId = (this.agentId !== null ? builder.createString(this.agentId!) : 0);

  CustomBot.startCustomBot(builder);
  CustomBot.addName(builder, name);
  CustomBot.addRootDir(builder, rootDir);
  CustomBot.addRunCommand(builder, runCommand);
  CustomBot.addLoadout(builder, loadout);
  CustomBot.addAgentId(builder, agentId);
  CustomBot.addHivemind(builder, this.hivemind);

  return CustomBot.endCustomBot(builder);
}
}
