// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum DebugRendering {
  /**
   * Renders are ignored unless explicitly enabled per-agent
   */
  OffByDefault = 0,

  /**
   * Rendering is enabled for everyone by default
   */
  OnByDefault = 1,

  /**
   * Ignore all render attempts at all times
   */
  AlwaysOff = 2
}
