// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Demolition mutator options.
 */
export enum DemolishMutator {
  Default = 0,
  Disabled = 1,
  FriendlyFire = 2,
  OnContact = 3,
  OnContactFF = 4,
  OnBallContact = 5,
  OnBallContactFF = 6,
  OnBallContactSilent = 7,
  OnBallContactFFSilent = 8
}
