// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { DesiredPhysics, DesiredPhysicsT } from '../../flat/flat/desired-physics.js';
import { Float, FloatT } from '../../flat/flat/float.js';


/**
 * A car state with nullable components.
 * Used for game state setting to define which part of a car's state should change.
 */
export class DesiredCarState implements flatbuffers.IUnpackableObject<DesiredCarStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DesiredCarState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDesiredCarState(bb:flatbuffers.ByteBuffer, obj?:DesiredCarState):DesiredCarState {
  return (obj || new DesiredCarState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDesiredCarState(bb:flatbuffers.ByteBuffer, obj?:DesiredCarState):DesiredCarState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DesiredCarState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

physics(obj?:DesiredPhysics):DesiredPhysics|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DesiredPhysics()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

boostAmount(obj?:Float):Float|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Float()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startDesiredCarState(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPhysics(builder:flatbuffers.Builder, physicsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, physicsOffset, 0);
}

static addBoostAmount(builder:flatbuffers.Builder, boostAmountOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, boostAmountOffset, 0);
}

static endDesiredCarState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): DesiredCarStateT {
  return new DesiredCarStateT(
    (this.physics() !== null ? this.physics()!.unpack() : null),
    (this.boostAmount() !== null ? this.boostAmount()!.unpack() : null)
  );
}


unpackTo(_o: DesiredCarStateT): void {
  _o.physics = (this.physics() !== null ? this.physics()!.unpack() : null);
  _o.boostAmount = (this.boostAmount() !== null ? this.boostAmount()!.unpack() : null);
}
}

export class DesiredCarStateT implements flatbuffers.IGeneratedObject {
constructor(
  public physics: DesiredPhysicsT|null = null,
  public boostAmount: FloatT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const physics = (this.physics !== null ? this.physics!.pack(builder) : 0);

  DesiredCarState.startDesiredCarState(builder);
  DesiredCarState.addPhysics(builder, physics);
  DesiredCarState.addBoostAmount(builder, (this.boostAmount !== null ? this.boostAmount!.pack(builder) : 0));

  return DesiredCarState.endDesiredCarState(builder);
}
}
