// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConsoleCommand, ConsoleCommandT } from '../../flat/flat/console-command.js';
import { DesiredBallState, DesiredBallStateT } from '../../flat/flat/desired-ball-state.js';
import { DesiredCarState, DesiredCarStateT } from '../../flat/flat/desired-car-state.js';
import { DesiredMatchInfo, DesiredMatchInfoT } from '../../flat/flat/desired-match-info.js';


/**
 * A game state with nullable subcomponents.
 * Used for game state setting to define which part of the game should change.
 * Values not set will not be updated.
 */
export class DesiredGameState implements flatbuffers.IUnpackableObject<DesiredGameStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DesiredGameState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDesiredGameState(bb:flatbuffers.ByteBuffer, obj?:DesiredGameState):DesiredGameState {
  return (obj || new DesiredGameState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDesiredGameState(bb:flatbuffers.ByteBuffer, obj?:DesiredGameState):DesiredGameState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DesiredGameState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of desired ball states.
 */
ballStates(index: number, obj?:DesiredBallState):DesiredBallState|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DesiredBallState()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

ballStatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * A list of desired car states.
 */
carStates(index: number, obj?:DesiredCarState):DesiredCarState|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new DesiredCarState()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

carStatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * The desired game info.
 */
matchInfo(obj?:DesiredMatchInfo):DesiredMatchInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new DesiredMatchInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * A list of console commands to execute.
 * See https://wiki.rlbot.org/framework/console-commands/ for a list of known commands.
 */
consoleCommands(index: number, obj?:ConsoleCommand):ConsoleCommand|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ConsoleCommand()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

consoleCommandsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDesiredGameState(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addBallStates(builder:flatbuffers.Builder, ballStatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ballStatesOffset, 0);
}

static createBallStatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBallStatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCarStates(builder:flatbuffers.Builder, carStatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, carStatesOffset, 0);
}

static createCarStatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCarStatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMatchInfo(builder:flatbuffers.Builder, matchInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, matchInfoOffset, 0);
}

static addConsoleCommands(builder:flatbuffers.Builder, consoleCommandsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, consoleCommandsOffset, 0);
}

static createConsoleCommandsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startConsoleCommandsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDesiredGameState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // ball_states
  builder.requiredField(offset, 6) // car_states
  builder.requiredField(offset, 10) // console_commands
  return offset;
}


unpack(): DesiredGameStateT {
  return new DesiredGameStateT(
    this.bb!.createObjList<DesiredBallState, DesiredBallStateT>(this.ballStates.bind(this), this.ballStatesLength()),
    this.bb!.createObjList<DesiredCarState, DesiredCarStateT>(this.carStates.bind(this), this.carStatesLength()),
    (this.matchInfo() !== null ? this.matchInfo()!.unpack() : null),
    this.bb!.createObjList<ConsoleCommand, ConsoleCommandT>(this.consoleCommands.bind(this), this.consoleCommandsLength())
  );
}


unpackTo(_o: DesiredGameStateT): void {
  _o.ballStates = this.bb!.createObjList<DesiredBallState, DesiredBallStateT>(this.ballStates.bind(this), this.ballStatesLength());
  _o.carStates = this.bb!.createObjList<DesiredCarState, DesiredCarStateT>(this.carStates.bind(this), this.carStatesLength());
  _o.matchInfo = (this.matchInfo() !== null ? this.matchInfo()!.unpack() : null);
  _o.consoleCommands = this.bb!.createObjList<ConsoleCommand, ConsoleCommandT>(this.consoleCommands.bind(this), this.consoleCommandsLength());
}
}

export class DesiredGameStateT implements flatbuffers.IGeneratedObject {
constructor(
  public ballStates: (DesiredBallStateT)[] = [],
  public carStates: (DesiredCarStateT)[] = [],
  public matchInfo: DesiredMatchInfoT|null = null,
  public consoleCommands: (ConsoleCommandT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const ballStates = DesiredGameState.createBallStatesVector(builder, builder.createObjectOffsetList(this.ballStates));
  const carStates = DesiredGameState.createCarStatesVector(builder, builder.createObjectOffsetList(this.carStates));
  const matchInfo = (this.matchInfo !== null ? this.matchInfo!.pack(builder) : 0);
  const consoleCommands = DesiredGameState.createConsoleCommandsVector(builder, builder.createObjectOffsetList(this.consoleCommands));

  DesiredGameState.startDesiredGameState(builder);
  DesiredGameState.addBallStates(builder, ballStates);
  DesiredGameState.addCarStates(builder, carStates);
  DesiredGameState.addMatchInfo(builder, matchInfo);
  DesiredGameState.addConsoleCommands(builder, consoleCommands);

  return DesiredGameState.endDesiredGameState(builder);
}
}
