// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Float, FloatT } from '../../flat/flat/float.js';


/**
 * Match info with nullable components.
 * Used for game state setting to define which part of the match info should change.
 */
export class DesiredMatchInfo implements flatbuffers.IUnpackableObject<DesiredMatchInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DesiredMatchInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDesiredMatchInfo(bb:flatbuffers.ByteBuffer, obj?:DesiredMatchInfo):DesiredMatchInfo {
  return (obj || new DesiredMatchInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDesiredMatchInfo(bb:flatbuffers.ByteBuffer, obj?:DesiredMatchInfo):DesiredMatchInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DesiredMatchInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The strength of gravity. Default is usually -650 depending on mutators.
 * To set gravity to 0, use 0.0000001 instead, as 0 will set gravity back to the default.
 */
worldGravityZ(obj?:Float):Float|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Float()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The game speed. Default is 1.0.
 */
gameSpeed(obj?:Float):Float|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Float()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startDesiredMatchInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addWorldGravityZ(builder:flatbuffers.Builder, worldGravityZOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, worldGravityZOffset, 0);
}

static addGameSpeed(builder:flatbuffers.Builder, gameSpeedOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, gameSpeedOffset, 0);
}

static endDesiredMatchInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): DesiredMatchInfoT {
  return new DesiredMatchInfoT(
    (this.worldGravityZ() !== null ? this.worldGravityZ()!.unpack() : null),
    (this.gameSpeed() !== null ? this.gameSpeed()!.unpack() : null)
  );
}


unpackTo(_o: DesiredMatchInfoT): void {
  _o.worldGravityZ = (this.worldGravityZ() !== null ? this.worldGravityZ()!.unpack() : null);
  _o.gameSpeed = (this.gameSpeed() !== null ? this.gameSpeed()!.unpack() : null);
}
}

export class DesiredMatchInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public worldGravityZ: FloatT|null = null,
  public gameSpeed: FloatT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  DesiredMatchInfo.startDesiredMatchInfo(builder);
  DesiredMatchInfo.addWorldGravityZ(builder, (this.worldGravityZ !== null ? this.worldGravityZ!.pack(builder) : 0));
  DesiredMatchInfo.addGameSpeed(builder, (this.gameSpeed !== null ? this.gameSpeed!.pack(builder) : 0));

  return DesiredMatchInfo.endDesiredMatchInfo(builder);
}
}
