// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Sent to core to indicate that you want to disconnect.
 * Sent from core to indicate that you should exit.
 */
export class DisconnectSignal implements flatbuffers.IUnpackableObject<DisconnectSignalT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DisconnectSignal {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDisconnectSignal(bb:flatbuffers.ByteBuffer, obj?:DisconnectSignal):DisconnectSignal {
  return (obj || new DisconnectSignal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDisconnectSignal(bb:flatbuffers.ByteBuffer, obj?:DisconnectSignal):DisconnectSignal {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DisconnectSignal()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startDisconnectSignal(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endDisconnectSignal(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDisconnectSignal(builder:flatbuffers.Builder):flatbuffers.Offset {
  DisconnectSignal.startDisconnectSignal(builder);
  return DisconnectSignal.endDisconnectSignal(builder);
}

unpack(): DisconnectSignalT {
  return new DisconnectSignalT();
}


unpackTo(_o: DisconnectSignalT): void {}
}

export class DisconnectSignalT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return DisconnectSignal.createDisconnectSignal(builder);
}
}
