// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Possible behaviours when a match is started while another match is in progress.
 */
export enum ExistingMatchBehavior {
  /**
   * Always restart the match, even if config is identical.
   */
  Restart = 0,

  /**
   * Never restart an existing match if possible, just try to remove or spawn cars to match the configuration.
   * If we are not in the middle of a match, a match will be started. Handy for LAN matches.
   */
  ContinueAndSpawn = 1,

  /**
   * Restart the match if any match settings differ.
   * No other otherwise.
   */
  RestartIfDifferent = 2
}
