// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Game event mutator options.
 */
export enum GameEventMutator {
  Default = 0,
  Haunted = 1,
  Rugby = 2
}
