// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Game speed mutator options.
 */
export enum GameSpeedMutator {
  Default = 0,
  SloMo = 1,
  TimeWarp = 2
}
