// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Various game modes.
 */
export enum GameMode {
  Soccar = 0,
  Hoops = 1,
  Dropshot = 2,
  Snowday = 3,
  Rumble = 4,
  Heatseeker = 5,
  Gridiron = 6,
  Knockout = 7
}
