// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Gravity mutator options.
 */
export enum GravityMutator {
  Default = 0,
  Low = 1,
  High = 2,
  SuperHigh = 3,
  Reverse = 4
}
