// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A normal human player.
 */
export class Human implements flatbuffers.IUnpackableObject<HumanT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Human {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHuman(bb:flatbuffers.ByteBuffer, obj?:Human):Human {
  return (obj || new Human()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHuman(bb:flatbuffers.ByteBuffer, obj?:Human):Human {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Human()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startHuman(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endHuman(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHuman(builder:flatbuffers.Builder):flatbuffers.Offset {
  Human.startHuman(builder);
  return Human.endHuman(builder);
}

unpack(): HumanT {
  return new HumanT();
}


unpackTo(_o: HumanT): void {}
}

export class HumanT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Human.createHuman(builder);
}
}
