// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Indicates that the session has finished all initialization and is ready to start receiving
 * game messages without delay.
 */
export class InitComplete implements flatbuffers.IUnpackableObject<InitCompleteT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InitComplete {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInitComplete(bb:flatbuffers.ByteBuffer, obj?:InitComplete):InitComplete {
  return (obj || new InitComplete()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInitComplete(bb:flatbuffers.ByteBuffer, obj?:InitComplete):InitComplete {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InitComplete()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startInitComplete(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endInitComplete(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInitComplete(builder:flatbuffers.Builder):flatbuffers.Offset {
  InitComplete.startInitComplete(builder);
  return InitComplete.endInitComplete(builder);
}

unpack(): InitCompleteT {
  return new InitCompleteT();
}


unpackTo(_o: InitCompleteT): void {}
}

export class InitCompleteT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return InitComplete.createInitComplete(builder);
}
}
