// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConnectionSettings, ConnectionSettingsT } from '../../flat/flat/connection-settings.js';
import { DesiredGameState, DesiredGameStateT } from '../../flat/flat/desired-game-state.js';
import { DisconnectSignal, DisconnectSignalT } from '../../flat/flat/disconnect-signal.js';
import { InitComplete, InitCompleteT } from '../../flat/flat/init-complete.js';
import { InterfaceMessage, unionToInterfaceMessage, unionListToInterfaceMessage } from '../../flat/flat/interface-message.js';
import { MatchComm, MatchCommT } from '../../flat/flat/match-comm.js';
import { MatchConfiguration, MatchConfigurationT } from '../../flat/flat/match-configuration.js';
import { PingRequest, PingRequestT } from '../../flat/flat/ping-request.js';
import { PingResponse, PingResponseT } from '../../flat/flat/ping-response.js';
import { PlayerInput, PlayerInputT } from '../../flat/flat/player-input.js';
import { RemoveRenderGroup, RemoveRenderGroupT } from '../../flat/flat/remove-render-group.js';
import { RenderGroup, RenderGroupT } from '../../flat/flat/render-group.js';
import { RenderingStatus, RenderingStatusT } from '../../flat/flat/rendering-status.js';
import { SetLoadout, SetLoadoutT } from '../../flat/flat/set-loadout.js';
import { StartCommand, StartCommandT } from '../../flat/flat/start-command.js';
import { StopCommand, StopCommandT } from '../../flat/flat/stop-command.js';


/**
 * Packet containing a InterfaceMessage
 */
export class InterfacePacket implements flatbuffers.IUnpackableObject<InterfacePacketT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InterfacePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInterfacePacket(bb:flatbuffers.ByteBuffer, obj?:InterfacePacket):InterfacePacket {
  return (obj || new InterfacePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInterfacePacket(bb:flatbuffers.ByteBuffer, obj?:InterfacePacket):InterfacePacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InterfacePacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageType():InterfaceMessage {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : InterfaceMessage.NONE;
}

message<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startInterfacePacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessageType(builder:flatbuffers.Builder, messageType:InterfaceMessage) {
  builder.addFieldInt8(0, messageType, InterfaceMessage.NONE);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endInterfacePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // message
  return offset;
}

static createInterfacePacket(builder:flatbuffers.Builder, messageType:InterfaceMessage, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  InterfacePacket.startInterfacePacket(builder);
  InterfacePacket.addMessageType(builder, messageType);
  InterfacePacket.addMessage(builder, messageOffset);
  return InterfacePacket.endInterfacePacket(builder);
}

unpack(): InterfacePacketT {
  return new InterfacePacketT(
    this.messageType(),
    (() => {
      const temp = unionToInterfaceMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: InterfacePacketT): void {
  _o.messageType = this.messageType();
  _o.message = (() => {
      const temp = unionToInterfaceMessage(this.messageType(), this.message.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class InterfacePacketT implements flatbuffers.IGeneratedObject {
constructor(
  public messageType: InterfaceMessage = InterfaceMessage.NONE,
  public message: ConnectionSettingsT|DesiredGameStateT|DisconnectSignalT|InitCompleteT|MatchCommT|MatchConfigurationT|PingRequestT|PingResponseT|PlayerInputT|RemoveRenderGroupT|RenderGroupT|RenderingStatusT|SetLoadoutT|StartCommandT|StopCommandT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = builder.createObjectOffset(this.message);

  return InterfacePacket.createInterfacePacket(builder,
    this.messageType,
    message
  );
}
}
