// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import {
  ConnectionSettings,
  ConnectionSettingsT,
} from "../../flat/flat/connection-settings.js";
import {
  DesiredGameState,
  DesiredGameStateT,
} from "../../flat/flat/desired-game-state.js";
import {
  DisconnectSignal,
  DisconnectSignalT,
} from "../../flat/flat/disconnect-signal.js";
import { InitComplete, InitCompleteT } from "../../flat/flat/init-complete.js";
import { MatchComm, MatchCommT } from "../../flat/flat/match-comm.js";
import {
  MatchConfiguration,
  MatchConfigurationT,
} from "../../flat/flat/match-configuration.js";
import { PingRequest, PingRequestT } from "../../flat/flat/ping-request.js";
import { PingResponse, PingResponseT } from "../../flat/flat/ping-response.js";
import { PlayerInput, PlayerInputT } from "../../flat/flat/player-input.js";
import {
  RemoveRenderGroup,
  RemoveRenderGroupT,
} from "../../flat/flat/remove-render-group.js";
import { RenderGroup, RenderGroupT } from "../../flat/flat/render-group.js";
import {
  RenderingStatus,
  RenderingStatusT,
} from "../../flat/flat/rendering-status.js";
import { SetLoadout, SetLoadoutT } from "../../flat/flat/set-loadout.js";
import { StartCommand, StartCommandT } from "../../flat/flat/start-command.js";
import { StopCommand, StopCommandT } from "../../flat/flat/stop-command.js";

/**
 * Messages sent from interfaces to core
 */
export enum InterfaceMessage {
  NONE = 0,

  /**
   * Sent to core to indicate that you want to disconnect.
   */
  DisconnectSignal = 1,

  /**
   * Starts a new match with a rlbot.toml file
   */
  StartCommand = 2,

  /**
   * Starts a new match from a MatchConfiguration
   */
  MatchConfiguration = 3,

  /**
   * Sent by bot agents to control their car(s)
   */
  PlayerInput = 4,

  /**
   * Sent by agents to state-set the game state.
   * `enable_state_setting` must be true in the MatchConfiguration.
   */
  DesiredGameState = 5,

  /**
   * Sent by agents to render lines and text in the game.
   */
  RenderGroup = 6,

  /**
   * Sent by agents to remove a render group.
   */
  RemoveRenderGroup = 7,

  /**
   * Agents may send a MatchComm packet to communicate with other agents,
   * core relays this to other agents. May be `team_only` if set.
   */
  MatchComm = 8,

  /**
   * Should be sent by agents immediately after connecting.
   * Tells core about who the connection represents and what data they want to receive.
   */
  ConnectionSettings = 9,

  /**
   * Ends the match and optionally the RLBotServer too.
   */
  StopCommand = 10,

  /**
   * Sent by sessions to change the loadout of their cars. Will always work if a loadout was not
   * specified in match settings and when sent before `InitComplete`. Ignored if state setting
   * was disabled in the match settings, and a loadout was set in match settings.
   */
  SetLoadout = 11,

  /**
   * Indicates that the session has finished all initialization and is ready to start receiving
   * game messages without delay. The match will not start until all sessions have sent this
   * message.
   */
  InitComplete = 12,

  /**
   * Requests for a specificed agent to have its ability to render changed.
   * This changed will then be broadcasted to all current connections.
   * Does nothing if rendering has been completely disabled.
   */
  RenderingStatus = 13,

  /**
   * Requests for server to send a PingResponse asap for measuring latency
   */
  PingRequest = 14,

  /**
   * Response to PingRequest for measuring latency
   */
  PingResponse = 15,
}

export function unionToInterfaceMessage(
  type: InterfaceMessage,
  accessor: (
    obj:
      | ConnectionSettings
      | DesiredGameState
      | DisconnectSignal
      | InitComplete
      | MatchComm
      | MatchConfiguration
      | PingRequest
      | PingResponse
      | PlayerInput
      | RemoveRenderGroup
      | RenderGroup
      | RenderingStatus
      | SetLoadout
      | StartCommand
      | StopCommand,
  ) =>
    | ConnectionSettings
    | DesiredGameState
    | DisconnectSignal
    | InitComplete
    | MatchComm
    | MatchConfiguration
    | PingRequest
    | PingResponse
    | PlayerInput
    | RemoveRenderGroup
    | RenderGroup
    | RenderingStatus
    | SetLoadout
    | StartCommand
    | StopCommand
    | null,
):
  | ConnectionSettings
  | DesiredGameState
  | DisconnectSignal
  | InitComplete
  | MatchComm
  | MatchConfiguration
  | PingRequest
  | PingResponse
  | PlayerInput
  | RemoveRenderGroup
  | RenderGroup
  | RenderingStatus
  | SetLoadout
  | StartCommand
  | StopCommand
  | null {
  switch (InterfaceMessage[type]) {
    case "NONE":
      return null;
    case "DisconnectSignal":
      return accessor(new DisconnectSignal())! as DisconnectSignal;
    case "StartCommand":
      return accessor(new StartCommand())! as StartCommand;
    case "MatchConfiguration":
      return accessor(new MatchConfiguration())! as MatchConfiguration;
    case "PlayerInput":
      return accessor(new PlayerInput())! as PlayerInput;
    case "DesiredGameState":
      return accessor(new DesiredGameState())! as DesiredGameState;
    case "RenderGroup":
      return accessor(new RenderGroup())! as RenderGroup;
    case "RemoveRenderGroup":
      return accessor(new RemoveRenderGroup())! as RemoveRenderGroup;
    case "MatchComm":
      return accessor(new MatchComm())! as MatchComm;
    case "ConnectionSettings":
      return accessor(new ConnectionSettings())! as ConnectionSettings;
    case "StopCommand":
      return accessor(new StopCommand())! as StopCommand;
    case "SetLoadout":
      return accessor(new SetLoadout())! as SetLoadout;
    case "InitComplete":
      return accessor(new InitComplete())! as InitComplete;
    case "RenderingStatus":
      return accessor(new RenderingStatus())! as RenderingStatus;
    case "PingRequest":
      return accessor(new PingRequest())! as PingRequest;
    case "PingResponse":
      return accessor(new PingResponse())! as PingResponse;
    default:
      return null;
  }
}

export function unionListToInterfaceMessage(
  type: InterfaceMessage,
  accessor: (
    index: number,
    obj:
      | ConnectionSettings
      | DesiredGameState
      | DisconnectSignal
      | InitComplete
      | MatchComm
      | MatchConfiguration
      | PingRequest
      | PingResponse
      | PlayerInput
      | RemoveRenderGroup
      | RenderGroup
      | RenderingStatus
      | SetLoadout
      | StartCommand
      | StopCommand,
  ) =>
    | ConnectionSettings
    | DesiredGameState
    | DisconnectSignal
    | InitComplete
    | MatchComm
    | MatchConfiguration
    | PingRequest
    | PingResponse
    | PlayerInput
    | RemoveRenderGroup
    | RenderGroup
    | RenderingStatus
    | SetLoadout
    | StartCommand
    | StopCommand
    | null,
  index: number,
):
  | ConnectionSettings
  | DesiredGameState
  | DisconnectSignal
  | InitComplete
  | MatchComm
  | MatchConfiguration
  | PingRequest
  | PingResponse
  | PlayerInput
  | RemoveRenderGroup
  | RenderGroup
  | RenderingStatus
  | SetLoadout
  | StartCommand
  | StopCommand
  | null {
  switch (InterfaceMessage[type]) {
    case "NONE":
      return null;
    case "DisconnectSignal":
      return accessor(index, new DisconnectSignal())! as DisconnectSignal;
    case "StartCommand":
      return accessor(index, new StartCommand())! as StartCommand;
    case "MatchConfiguration":
      return accessor(index, new MatchConfiguration())! as MatchConfiguration;
    case "PlayerInput":
      return accessor(index, new PlayerInput())! as PlayerInput;
    case "DesiredGameState":
      return accessor(index, new DesiredGameState())! as DesiredGameState;
    case "RenderGroup":
      return accessor(index, new RenderGroup())! as RenderGroup;
    case "RemoveRenderGroup":
      return accessor(index, new RemoveRenderGroup())! as RemoveRenderGroup;
    case "MatchComm":
      return accessor(index, new MatchComm())! as MatchComm;
    case "ConnectionSettings":
      return accessor(index, new ConnectionSettings())! as ConnectionSettings;
    case "StopCommand":
      return accessor(index, new StopCommand())! as StopCommand;
    case "SetLoadout":
      return accessor(index, new SetLoadout())! as SetLoadout;
    case "InitComplete":
      return accessor(index, new InitComplete())! as InitComplete;
    case "RenderingStatus":
      return accessor(index, new RenderingStatus())! as RenderingStatus;
    case "PingRequest":
      return accessor(index, new PingRequest())! as PingRequest;
    case "PingResponse":
      return accessor(index, new PingResponse())! as PingResponse;
    default:
      return null;
  }
}
