// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum JumpMutator {
  Default = 0,
  Grounded = 1,
  Two = 2,
  Three = 3,
  Four = 4,
  Unlimited = 5,
  NoJumps = 6
}
