// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Possible to launch Rocket League.
 */
export enum Launcher {
  Steam = 0,
  Epic = 1,

  /**
   * E.g. if you use Legendary.
   * The game path is specified in the MatchConfiguration.
   */
  Custom = 2,
  NoLaunch = 3
}
