// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { RenderAnchor, RenderAnchorT } from '../../flat/flat/render-anchor.js';


/**
 * A RenderMessage for a line in 3D space between two RenderAnchors.
 */
export class Line3D implements flatbuffers.IUnpackableObject<Line3DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Line3D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLine3D(bb:flatbuffers.ByteBuffer, obj?:Line3D):Line3D {
  return (obj || new Line3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLine3D(bb:flatbuffers.ByteBuffer, obj?:Line3D):Line3D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Line3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start(obj?:RenderAnchor):RenderAnchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new RenderAnchor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

end(obj?:RenderAnchor):RenderAnchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RenderAnchor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startLine3D(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, endOffset, 0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, colorOffset, 0);
}

static endLine3D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // start
  builder.requiredField(offset, 6) // end
  builder.requiredField(offset, 8) // color
  return offset;
}


unpack(): Line3DT {
  return new Line3DT(
    (this.start() !== null ? this.start()!.unpack() : null),
    (this.end() !== null ? this.end()!.unpack() : null),
    (this.color() !== null ? this.color()!.unpack() : null)
  );
}


unpackTo(_o: Line3DT): void {
  _o.start = (this.start() !== null ? this.start()!.unpack() : null);
  _o.end = (this.end() !== null ? this.end()!.unpack() : null);
  _o.color = (this.color() !== null ? this.color()!.unpack() : null);
}
}

export class Line3DT implements flatbuffers.IGeneratedObject {
constructor(
  public start: RenderAnchorT|null = null,
  public end: RenderAnchorT|null = null,
  public color: ColorT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const start = (this.start !== null ? this.start!.pack(builder) : 0);
  const end = (this.end !== null ? this.end!.pack(builder) : 0);

  Line3D.startLine3D(builder);
  Line3D.addStart(builder, start);
  Line3D.addEnd(builder, end);
  Line3D.addColor(builder, (this.color !== null ? this.color!.pack(builder) : 0));

  return Line3D.endLine3D(builder);
}
}
