// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Possible phases of the match.
 */
export enum MatchPhase {
  /**
   * Match has not been created yet.
   */
  Inactive = 0,

  /**
   * 3-2-1 countdown of a kickoff.
   */
  Countdown = 1,

  /**
   * After kickoff countdown, but before ball has been hit.
   * The match automatically proceeds to Active after 2 seconds.
   */
  Kickoff = 2,

  /**
   * The ball is in play and time is ticking.
   */
  Active = 3,

  /**
   * A goal was just scored. Waiting for replay to start.
   */
  GoalScored = 4,

  /**
   * Goal replay is being shown.
   */
  Replay = 5,

  /**
   * The match is paused.
   */
  Paused = 6,

  /**
   * The match has ended.
   */
  Ended = 7
}
