// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Match length mutator options.
 */
export enum MatchLengthMutator {
  FiveMinutes = 0,
  TenMinutes = 1,
  TwentyMinutes = 2,
  Unlimited = 3
}
