// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Max score mutator options.
 */
export enum MaxScoreMutator {
  Unlimited = 0,
  OneGoal = 1,
  ThreeGoals = 2,
  FiveGoals = 3,
  SevenGoals = 4,
  TenGoals = 5,
  TwentyGoals = 6,
  ThirtyGoals = 7,
  FortyGoals = 8,
  FiftyGoals = 9,
  SixtyGoals = 10,
  SeventyGoals = 11,
  EightyGoals = 12,
  NinetyGoals = 13,
  HundredGoals = 14
}
