// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Max time mutator options.
 */
export enum MaxTimeMutator {
  Unlimited = 0,
  ElevenMinutes = 1
}
