// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Multi ball mutator options.
 */
export enum MultiBallMutator {
  One = 0,
  Two = 1,
  Four = 2,
  Six = 3
}
