// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AerialGoalScoreMutator } from '../../flat/flat/aerial-goal-score-mutator.js';
import { AssistGoalScoreMutator } from '../../flat/flat/assist-goal-score-mutator.js';
import { AudioMutator } from '../../flat/flat/audio-mutator.js';
import { BallBouncinessMutator } from '../../flat/flat/ball-bounciness-mutator.js';
import { BallGravityMutator } from '../../flat/flat/ball-gravity-mutator.js';
import { BallMaxSpeedMutator } from '../../flat/flat/ball-max-speed-mutator.js';
import { BallSizeMutator } from '../../flat/flat/ball-size-mutator.js';
import { BallTypeMutator } from '../../flat/flat/ball-type-mutator.js';
import { BallWeightMutator } from '../../flat/flat/ball-weight-mutator.js';
import { BoostAmountMutator } from '../../flat/flat/boost-amount-mutator.js';
import { BoostStrengthMutator } from '../../flat/flat/boost-strength-mutator.js';
import { DemolishMutator } from '../../flat/flat/demolish-mutator.js';
import { DemolishScoreMutator } from '../../flat/flat/demolish-score-mutator.js';
import { DodgeTimerMutator } from '../../flat/flat/dodge-timer-mutator.js';
import { GameEventMutator } from '../../flat/flat/game-event-mutator.js';
import { GameSpeedMutator } from '../../flat/flat/game-speed-mutator.js';
import { GravityMutator } from '../../flat/flat/gravity-mutator.js';
import { InputRestrictionMutator } from '../../flat/flat/input-restriction-mutator.js';
import { JumpMutator } from '../../flat/flat/jump-mutator.js';
import { MatchLengthMutator } from '../../flat/flat/match-length-mutator.js';
import { MaxScoreMutator } from '../../flat/flat/max-score-mutator.js';
import { MaxTimeMutator } from '../../flat/flat/max-time-mutator.js';
import { MultiBallMutator } from '../../flat/flat/multi-ball-mutator.js';
import { NormalGoalScoreMutator } from '../../flat/flat/normal-goal-score-mutator.js';
import { OvertimeMutator } from '../../flat/flat/overtime-mutator.js';
import { PossessionScoreMutator } from '../../flat/flat/possession-score-mutator.js';
import { RespawnTimeMutator } from '../../flat/flat/respawn-time-mutator.js';
import { RumbleMutator } from '../../flat/flat/rumble-mutator.js';
import { ScoringRuleMutator } from '../../flat/flat/scoring-rule-mutator.js';
import { SeriesLengthMutator } from '../../flat/flat/series-length-mutator.js';
import { StaleBallMutator } from '../../flat/flat/stale-ball-mutator.js';
import { TerritoryMutator } from '../../flat/flat/territory-mutator.js';


/**
 * All mutators options.
 */
export class MutatorSettings implements flatbuffers.IUnpackableObject<MutatorSettingsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MutatorSettings {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMutatorSettings(bb:flatbuffers.ByteBuffer, obj?:MutatorSettings):MutatorSettings {
  return (obj || new MutatorSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMutatorSettings(bb:flatbuffers.ByteBuffer, obj?:MutatorSettings):MutatorSettings {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MutatorSettings()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Duration of the match.
 */
matchLength():MatchLengthMutator {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MatchLengthMutator.FiveMinutes;
}

/**
 * Max score of match. If this score is reached, the team immediately wins.
 */
maxScore():MaxScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MaxScoreMutator.Unlimited;
}

/**
 * The number of balls.
 */
multiBall():MultiBallMutator {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MultiBallMutator.One;
}

/**
 * The overtime rules and tiebreaker.
 */
overtime():OvertimeMutator {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : OvertimeMutator.Unlimited;
}

/**
 * The series length.
 */
seriesLength():SeriesLengthMutator {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SeriesLengthMutator.Unlimited;
}

/**
 * A game speed multiplier.
 */
gameSpeed():GameSpeedMutator {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : GameSpeedMutator.Default;
}

/**
 * Ball max speed.
 */
ballMaxSpeed():BallMaxSpeedMutator {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallMaxSpeedMutator.Default;
}

/**
 * Ball type and shape.
 */
ballType():BallTypeMutator {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallTypeMutator.Default;
}

/**
 * Ball weight and how much is curves.
 */
ballWeight():BallWeightMutator {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallWeightMutator.Default;
}

/**
 * Ball size.
 */
ballSize():BallSizeMutator {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallSizeMutator.Default;
}

/**
 * Ball bounciness.
 */
ballBounciness():BallBouncinessMutator {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallBouncinessMutator.Default;
}

/**
 * Boost amount/recharge.
 */
boostAmount():BoostAmountMutator {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BoostAmountMutator.NormalBoost;
}

/**
 * Rumble item rules.
 */
rumble():RumbleMutator {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RumbleMutator.Off;
}

/**
 * Boost strength multiplier.
 */
boostStrength():BoostStrengthMutator {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BoostStrengthMutator.One;
}

/**
 * Strength of gravity.
 */
gravity():GravityMutator {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : GravityMutator.Default;
}

/**
 * Demolition conditions.
 */
demolish():DemolishMutator {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DemolishMutator.Default;
}

/**
 * Demolition respawn time.
 */
respawnTime():RespawnTimeMutator {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RespawnTimeMutator.ThreeSeconds;
}

/**
 * Max real-time duration of match including kickoff, replays, and more.
 * If the score is tied upon time-out, the number of shots determine the winner.
 */
maxTime():MaxTimeMutator {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MaxTimeMutator.Unlimited;
}

/**
 * Additional game behaviour for custom modes.
 */
gameEvent():GameEventMutator {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : GameEventMutator.Default;
}

/**
 * Additional audio options for custom modes.
 */
audio():AudioMutator {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AudioMutator.Default;
}

/**
 * Ball gravity.
 */
ballGravity():BallGravityMutator {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BallGravityMutator.Default;
}

/**
 * Territory mutator.
 */
territory():TerritoryMutator {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TerritoryMutator.Off;
}

/**
 * Stale ball mutator.
 */
staleBall():StaleBallMutator {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StaleBallMutator.Unlimited;
}

/**
 * Jumps mutator.
 */
jump():JumpMutator {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : JumpMutator.Default;
}

/**
 * Dodge timer mutator.
 */
dodgeTimer():DodgeTimerMutator {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DodgeTimerMutator.OnePointTwentyFiveSeconds;
}

/**
 * Possession score mutator.
 */
possessionScore():PossessionScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PossessionScoreMutator.Off;
}

/**
 * Demolish score mutator.
 */
demolishScore():DemolishScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : DemolishScoreMutator.Zero;
}

/**
 * Normal goal score mutator.
 */
normalGoalScore():NormalGoalScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : NormalGoalScoreMutator.One;
}

/**
 * Aerial goal score mutator.
 */
aerialGoalScore():AerialGoalScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AerialGoalScoreMutator.One;
}

/**
 * Assist goal score mutator.
 */
assistGoalScore():AssistGoalScoreMutator {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : AssistGoalScoreMutator.Zero;
}

/**
 * Player input restriction mutator.
 */
inputRestriction():InputRestrictionMutator {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : InputRestrictionMutator.Default;
}

/**
 * Additional rules about scoring (ball-goal interaction).
 */
scoringRule():ScoringRuleMutator {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ScoringRuleMutator.Default;
}

static startMutatorSettings(builder:flatbuffers.Builder) {
  builder.startObject(32);
}

static addMatchLength(builder:flatbuffers.Builder, matchLength:MatchLengthMutator) {
  builder.addFieldInt8(0, matchLength, MatchLengthMutator.FiveMinutes);
}

static addMaxScore(builder:flatbuffers.Builder, maxScore:MaxScoreMutator) {
  builder.addFieldInt8(1, maxScore, MaxScoreMutator.Unlimited);
}

static addMultiBall(builder:flatbuffers.Builder, multiBall:MultiBallMutator) {
  builder.addFieldInt8(2, multiBall, MultiBallMutator.One);
}

static addOvertime(builder:flatbuffers.Builder, overtime:OvertimeMutator) {
  builder.addFieldInt8(3, overtime, OvertimeMutator.Unlimited);
}

static addSeriesLength(builder:flatbuffers.Builder, seriesLength:SeriesLengthMutator) {
  builder.addFieldInt8(4, seriesLength, SeriesLengthMutator.Unlimited);
}

static addGameSpeed(builder:flatbuffers.Builder, gameSpeed:GameSpeedMutator) {
  builder.addFieldInt8(5, gameSpeed, GameSpeedMutator.Default);
}

static addBallMaxSpeed(builder:flatbuffers.Builder, ballMaxSpeed:BallMaxSpeedMutator) {
  builder.addFieldInt8(6, ballMaxSpeed, BallMaxSpeedMutator.Default);
}

static addBallType(builder:flatbuffers.Builder, ballType:BallTypeMutator) {
  builder.addFieldInt8(7, ballType, BallTypeMutator.Default);
}

static addBallWeight(builder:flatbuffers.Builder, ballWeight:BallWeightMutator) {
  builder.addFieldInt8(8, ballWeight, BallWeightMutator.Default);
}

static addBallSize(builder:flatbuffers.Builder, ballSize:BallSizeMutator) {
  builder.addFieldInt8(9, ballSize, BallSizeMutator.Default);
}

static addBallBounciness(builder:flatbuffers.Builder, ballBounciness:BallBouncinessMutator) {
  builder.addFieldInt8(10, ballBounciness, BallBouncinessMutator.Default);
}

static addBoostAmount(builder:flatbuffers.Builder, boostAmount:BoostAmountMutator) {
  builder.addFieldInt8(11, boostAmount, BoostAmountMutator.NormalBoost);
}

static addRumble(builder:flatbuffers.Builder, rumble:RumbleMutator) {
  builder.addFieldInt8(12, rumble, RumbleMutator.Off);
}

static addBoostStrength(builder:flatbuffers.Builder, boostStrength:BoostStrengthMutator) {
  builder.addFieldInt8(13, boostStrength, BoostStrengthMutator.One);
}

static addGravity(builder:flatbuffers.Builder, gravity:GravityMutator) {
  builder.addFieldInt8(14, gravity, GravityMutator.Default);
}

static addDemolish(builder:flatbuffers.Builder, demolish:DemolishMutator) {
  builder.addFieldInt8(15, demolish, DemolishMutator.Default);
}

static addRespawnTime(builder:flatbuffers.Builder, respawnTime:RespawnTimeMutator) {
  builder.addFieldInt8(16, respawnTime, RespawnTimeMutator.ThreeSeconds);
}

static addMaxTime(builder:flatbuffers.Builder, maxTime:MaxTimeMutator) {
  builder.addFieldInt8(17, maxTime, MaxTimeMutator.Unlimited);
}

static addGameEvent(builder:flatbuffers.Builder, gameEvent:GameEventMutator) {
  builder.addFieldInt8(18, gameEvent, GameEventMutator.Default);
}

static addAudio(builder:flatbuffers.Builder, audio:AudioMutator) {
  builder.addFieldInt8(19, audio, AudioMutator.Default);
}

static addBallGravity(builder:flatbuffers.Builder, ballGravity:BallGravityMutator) {
  builder.addFieldInt8(20, ballGravity, BallGravityMutator.Default);
}

static addTerritory(builder:flatbuffers.Builder, territory:TerritoryMutator) {
  builder.addFieldInt8(21, territory, TerritoryMutator.Off);
}

static addStaleBall(builder:flatbuffers.Builder, staleBall:StaleBallMutator) {
  builder.addFieldInt8(22, staleBall, StaleBallMutator.Unlimited);
}

static addJump(builder:flatbuffers.Builder, jump:JumpMutator) {
  builder.addFieldInt8(23, jump, JumpMutator.Default);
}

static addDodgeTimer(builder:flatbuffers.Builder, dodgeTimer:DodgeTimerMutator) {
  builder.addFieldInt8(24, dodgeTimer, DodgeTimerMutator.OnePointTwentyFiveSeconds);
}

static addPossessionScore(builder:flatbuffers.Builder, possessionScore:PossessionScoreMutator) {
  builder.addFieldInt8(25, possessionScore, PossessionScoreMutator.Off);
}

static addDemolishScore(builder:flatbuffers.Builder, demolishScore:DemolishScoreMutator) {
  builder.addFieldInt8(26, demolishScore, DemolishScoreMutator.Zero);
}

static addNormalGoalScore(builder:flatbuffers.Builder, normalGoalScore:NormalGoalScoreMutator) {
  builder.addFieldInt8(27, normalGoalScore, NormalGoalScoreMutator.One);
}

static addAerialGoalScore(builder:flatbuffers.Builder, aerialGoalScore:AerialGoalScoreMutator) {
  builder.addFieldInt8(28, aerialGoalScore, AerialGoalScoreMutator.One);
}

static addAssistGoalScore(builder:flatbuffers.Builder, assistGoalScore:AssistGoalScoreMutator) {
  builder.addFieldInt8(29, assistGoalScore, AssistGoalScoreMutator.Zero);
}

static addInputRestriction(builder:flatbuffers.Builder, inputRestriction:InputRestrictionMutator) {
  builder.addFieldInt8(30, inputRestriction, InputRestrictionMutator.Default);
}

static addScoringRule(builder:flatbuffers.Builder, scoringRule:ScoringRuleMutator) {
  builder.addFieldInt8(31, scoringRule, ScoringRuleMutator.Default);
}

static endMutatorSettings(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMutatorSettings(builder:flatbuffers.Builder, matchLength:MatchLengthMutator, maxScore:MaxScoreMutator, multiBall:MultiBallMutator, overtime:OvertimeMutator, seriesLength:SeriesLengthMutator, gameSpeed:GameSpeedMutator, ballMaxSpeed:BallMaxSpeedMutator, ballType:BallTypeMutator, ballWeight:BallWeightMutator, ballSize:BallSizeMutator, ballBounciness:BallBouncinessMutator, boostAmount:BoostAmountMutator, rumble:RumbleMutator, boostStrength:BoostStrengthMutator, gravity:GravityMutator, demolish:DemolishMutator, respawnTime:RespawnTimeMutator, maxTime:MaxTimeMutator, gameEvent:GameEventMutator, audio:AudioMutator, ballGravity:BallGravityMutator, territory:TerritoryMutator, staleBall:StaleBallMutator, jump:JumpMutator, dodgeTimer:DodgeTimerMutator, possessionScore:PossessionScoreMutator, demolishScore:DemolishScoreMutator, normalGoalScore:NormalGoalScoreMutator, aerialGoalScore:AerialGoalScoreMutator, assistGoalScore:AssistGoalScoreMutator, inputRestriction:InputRestrictionMutator, scoringRule:ScoringRuleMutator):flatbuffers.Offset {
  MutatorSettings.startMutatorSettings(builder);
  MutatorSettings.addMatchLength(builder, matchLength);
  MutatorSettings.addMaxScore(builder, maxScore);
  MutatorSettings.addMultiBall(builder, multiBall);
  MutatorSettings.addOvertime(builder, overtime);
  MutatorSettings.addSeriesLength(builder, seriesLength);
  MutatorSettings.addGameSpeed(builder, gameSpeed);
  MutatorSettings.addBallMaxSpeed(builder, ballMaxSpeed);
  MutatorSettings.addBallType(builder, ballType);
  MutatorSettings.addBallWeight(builder, ballWeight);
  MutatorSettings.addBallSize(builder, ballSize);
  MutatorSettings.addBallBounciness(builder, ballBounciness);
  MutatorSettings.addBoostAmount(builder, boostAmount);
  MutatorSettings.addRumble(builder, rumble);
  MutatorSettings.addBoostStrength(builder, boostStrength);
  MutatorSettings.addGravity(builder, gravity);
  MutatorSettings.addDemolish(builder, demolish);
  MutatorSettings.addRespawnTime(builder, respawnTime);
  MutatorSettings.addMaxTime(builder, maxTime);
  MutatorSettings.addGameEvent(builder, gameEvent);
  MutatorSettings.addAudio(builder, audio);
  MutatorSettings.addBallGravity(builder, ballGravity);
  MutatorSettings.addTerritory(builder, territory);
  MutatorSettings.addStaleBall(builder, staleBall);
  MutatorSettings.addJump(builder, jump);
  MutatorSettings.addDodgeTimer(builder, dodgeTimer);
  MutatorSettings.addPossessionScore(builder, possessionScore);
  MutatorSettings.addDemolishScore(builder, demolishScore);
  MutatorSettings.addNormalGoalScore(builder, normalGoalScore);
  MutatorSettings.addAerialGoalScore(builder, aerialGoalScore);
  MutatorSettings.addAssistGoalScore(builder, assistGoalScore);
  MutatorSettings.addInputRestriction(builder, inputRestriction);
  MutatorSettings.addScoringRule(builder, scoringRule);
  return MutatorSettings.endMutatorSettings(builder);
}

unpack(): MutatorSettingsT {
  return new MutatorSettingsT(
    this.matchLength(),
    this.maxScore(),
    this.multiBall(),
    this.overtime(),
    this.seriesLength(),
    this.gameSpeed(),
    this.ballMaxSpeed(),
    this.ballType(),
    this.ballWeight(),
    this.ballSize(),
    this.ballBounciness(),
    this.boostAmount(),
    this.rumble(),
    this.boostStrength(),
    this.gravity(),
    this.demolish(),
    this.respawnTime(),
    this.maxTime(),
    this.gameEvent(),
    this.audio(),
    this.ballGravity(),
    this.territory(),
    this.staleBall(),
    this.jump(),
    this.dodgeTimer(),
    this.possessionScore(),
    this.demolishScore(),
    this.normalGoalScore(),
    this.aerialGoalScore(),
    this.assistGoalScore(),
    this.inputRestriction(),
    this.scoringRule()
  );
}


unpackTo(_o: MutatorSettingsT): void {
  _o.matchLength = this.matchLength();
  _o.maxScore = this.maxScore();
  _o.multiBall = this.multiBall();
  _o.overtime = this.overtime();
  _o.seriesLength = this.seriesLength();
  _o.gameSpeed = this.gameSpeed();
  _o.ballMaxSpeed = this.ballMaxSpeed();
  _o.ballType = this.ballType();
  _o.ballWeight = this.ballWeight();
  _o.ballSize = this.ballSize();
  _o.ballBounciness = this.ballBounciness();
  _o.boostAmount = this.boostAmount();
  _o.rumble = this.rumble();
  _o.boostStrength = this.boostStrength();
  _o.gravity = this.gravity();
  _o.demolish = this.demolish();
  _o.respawnTime = this.respawnTime();
  _o.maxTime = this.maxTime();
  _o.gameEvent = this.gameEvent();
  _o.audio = this.audio();
  _o.ballGravity = this.ballGravity();
  _o.territory = this.territory();
  _o.staleBall = this.staleBall();
  _o.jump = this.jump();
  _o.dodgeTimer = this.dodgeTimer();
  _o.possessionScore = this.possessionScore();
  _o.demolishScore = this.demolishScore();
  _o.normalGoalScore = this.normalGoalScore();
  _o.aerialGoalScore = this.aerialGoalScore();
  _o.assistGoalScore = this.assistGoalScore();
  _o.inputRestriction = this.inputRestriction();
  _o.scoringRule = this.scoringRule();
}
}

export class MutatorSettingsT implements flatbuffers.IGeneratedObject {
constructor(
  public matchLength: MatchLengthMutator = MatchLengthMutator.FiveMinutes,
  public maxScore: MaxScoreMutator = MaxScoreMutator.Unlimited,
  public multiBall: MultiBallMutator = MultiBallMutator.One,
  public overtime: OvertimeMutator = OvertimeMutator.Unlimited,
  public seriesLength: SeriesLengthMutator = SeriesLengthMutator.Unlimited,
  public gameSpeed: GameSpeedMutator = GameSpeedMutator.Default,
  public ballMaxSpeed: BallMaxSpeedMutator = BallMaxSpeedMutator.Default,
  public ballType: BallTypeMutator = BallTypeMutator.Default,
  public ballWeight: BallWeightMutator = BallWeightMutator.Default,
  public ballSize: BallSizeMutator = BallSizeMutator.Default,
  public ballBounciness: BallBouncinessMutator = BallBouncinessMutator.Default,
  public boostAmount: BoostAmountMutator = BoostAmountMutator.NormalBoost,
  public rumble: RumbleMutator = RumbleMutator.Off,
  public boostStrength: BoostStrengthMutator = BoostStrengthMutator.One,
  public gravity: GravityMutator = GravityMutator.Default,
  public demolish: DemolishMutator = DemolishMutator.Default,
  public respawnTime: RespawnTimeMutator = RespawnTimeMutator.ThreeSeconds,
  public maxTime: MaxTimeMutator = MaxTimeMutator.Unlimited,
  public gameEvent: GameEventMutator = GameEventMutator.Default,
  public audio: AudioMutator = AudioMutator.Default,
  public ballGravity: BallGravityMutator = BallGravityMutator.Default,
  public territory: TerritoryMutator = TerritoryMutator.Off,
  public staleBall: StaleBallMutator = StaleBallMutator.Unlimited,
  public jump: JumpMutator = JumpMutator.Default,
  public dodgeTimer: DodgeTimerMutator = DodgeTimerMutator.OnePointTwentyFiveSeconds,
  public possessionScore: PossessionScoreMutator = PossessionScoreMutator.Off,
  public demolishScore: DemolishScoreMutator = DemolishScoreMutator.Zero,
  public normalGoalScore: NormalGoalScoreMutator = NormalGoalScoreMutator.One,
  public aerialGoalScore: AerialGoalScoreMutator = AerialGoalScoreMutator.One,
  public assistGoalScore: AssistGoalScoreMutator = AssistGoalScoreMutator.Zero,
  public inputRestriction: InputRestrictionMutator = InputRestrictionMutator.Default,
  public scoringRule: ScoringRuleMutator = ScoringRuleMutator.Default
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return MutatorSettings.createMutatorSettings(builder,
    this.matchLength,
    this.maxScore,
    this.multiBall,
    this.overtime,
    this.seriesLength,
    this.gameSpeed,
    this.ballMaxSpeed,
    this.ballType,
    this.ballWeight,
    this.ballSize,
    this.ballBounciness,
    this.boostAmount,
    this.rumble,
    this.boostStrength,
    this.gravity,
    this.demolish,
    this.respawnTime,
    this.maxTime,
    this.gameEvent,
    this.audio,
    this.ballGravity,
    this.territory,
    this.staleBall,
    this.jump,
    this.dodgeTimer,
    this.possessionScore,
    this.demolishScore,
    this.normalGoalScore,
    this.aerialGoalScore,
    this.assistGoalScore,
    this.inputRestriction,
    this.scoringRule
  );
}
}
