// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum NormalGoalScoreMutator {
  One = 0,
  Zero = 1,
  Two = 2,
  Three = 3,
  Five = 4,
  Ten = 5
}
