// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Overtime mutator options.
 */
export enum OvertimeMutator {
  Unlimited = 0,
  FiveMaxFirstScore = 1,
  FiveMaxRandomTeam = 2
}
