// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Rotator, RotatorT } from '../../flat/flat/rotator.js';
import { Vector3, Vector3T } from '../../flat/flat/vector3.js';


/**
 * The physical state of an object.
 */
export class Physics implements flatbuffers.IUnpackableObject<PhysicsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Physics {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

location(obj?:Vector3):Vector3|null {
  return (obj || new Vector3()).__init(this.bb_pos, this.bb!);
}

rotation(obj?:Rotator):Rotator|null {
  return (obj || new Rotator()).__init(this.bb_pos + 12, this.bb!);
}

velocity(obj?:Vector3):Vector3|null {
  return (obj || new Vector3()).__init(this.bb_pos + 24, this.bb!);
}

angularVelocity(obj?:Vector3):Vector3|null {
  return (obj || new Vector3()).__init(this.bb_pos + 36, this.bb!);
}

static sizeOf():number {
  return 48;
}

static createPhysics(builder:flatbuffers.Builder, location_x: number, location_y: number, location_z: number, rotation_pitch: number, rotation_yaw: number, rotation_roll: number, velocity_x: number, velocity_y: number, velocity_z: number, angular_velocity_x: number, angular_velocity_y: number, angular_velocity_z: number):flatbuffers.Offset {
  builder.prep(4, 48);
  builder.prep(4, 12);
  builder.writeFloat32(angular_velocity_z);
  builder.writeFloat32(angular_velocity_y);
  builder.writeFloat32(angular_velocity_x);
  builder.prep(4, 12);
  builder.writeFloat32(velocity_z);
  builder.writeFloat32(velocity_y);
  builder.writeFloat32(velocity_x);
  builder.prep(4, 12);
  builder.writeFloat32(rotation_roll);
  builder.writeFloat32(rotation_yaw);
  builder.writeFloat32(rotation_pitch);
  builder.prep(4, 12);
  builder.writeFloat32(location_z);
  builder.writeFloat32(location_y);
  builder.writeFloat32(location_x);
  return builder.offset();
}


unpack(): PhysicsT {
  return new PhysicsT(
    (this.location() !== null ? this.location()!.unpack() : null),
    (this.rotation() !== null ? this.rotation()!.unpack() : null),
    (this.velocity() !== null ? this.velocity()!.unpack() : null),
    (this.angularVelocity() !== null ? this.angularVelocity()!.unpack() : null)
  );
}


unpackTo(_o: PhysicsT): void {
  _o.location = (this.location() !== null ? this.location()!.unpack() : null);
  _o.rotation = (this.rotation() !== null ? this.rotation()!.unpack() : null);
  _o.velocity = (this.velocity() !== null ? this.velocity()!.unpack() : null);
  _o.angularVelocity = (this.angularVelocity() !== null ? this.angularVelocity()!.unpack() : null);
}
}

export class PhysicsT implements flatbuffers.IGeneratedObject {
constructor(
  public location: Vector3T|null = null,
  public rotation: RotatorT|null = null,
  public velocity: Vector3T|null = null,
  public angularVelocity: Vector3T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Physics.createPhysics(builder,
    (this.location?.x ?? 0),
    (this.location?.y ?? 0),
    (this.location?.z ?? 0),
    (this.rotation?.pitch ?? 0),
    (this.rotation?.yaw ?? 0),
    (this.rotation?.roll ?? 0),
    (this.velocity?.x ?? 0),
    (this.velocity?.y ?? 0),
    (this.velocity?.z ?? 0),
    (this.angularVelocity?.x ?? 0),
    (this.angularVelocity?.y ?? 0),
    (this.angularVelocity?.z ?? 0)
  );
}
}
