// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CustomBot, CustomBotT } from '../../flat/flat/custom-bot.js';
import { Human, HumanT } from '../../flat/flat/human.js';
import { PlayerClass, unionToPlayerClass, unionListToPlayerClass } from '../../flat/flat/player-class.js';
import { PsyonixBot, PsyonixBotT } from '../../flat/flat/psyonix-bot.js';


/**
 * A PlayerConfiguration defines a player of a match.
 */
export class PlayerConfiguration implements flatbuffers.IUnpackableObject<PlayerConfigurationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerConfiguration(bb:flatbuffers.ByteBuffer, obj?:PlayerConfiguration):PlayerConfiguration {
  return (obj || new PlayerConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerConfiguration(bb:flatbuffers.ByteBuffer, obj?:PlayerConfiguration):PlayerConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

varietyType():PlayerClass {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PlayerClass.NONE;
}

/**
 * The type of the player, i.e. human, Psyonix bot, or a custom bot.
 */
variety<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

/**
 * The team of the player. Blue is 0, orange is 1.
 */
team():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The value will be set by RLBot and is always overriden.
 * This value is mostly used internally to keep track of participants in the match.
 * The player id can be used to find the corresponding player in the GamePacket.
 */
playerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPlayerConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addVarietyType(builder:flatbuffers.Builder, varietyType:PlayerClass) {
  builder.addFieldInt8(0, varietyType, PlayerClass.NONE);
}

static addVariety(builder:flatbuffers.Builder, varietyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, varietyOffset, 0);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt32(2, team, 0);
}

static addPlayerId(builder:flatbuffers.Builder, playerId:number) {
  builder.addFieldInt32(3, playerId, 0);
}

static endPlayerConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // variety
  return offset;
}

static createPlayerConfiguration(builder:flatbuffers.Builder, varietyType:PlayerClass, varietyOffset:flatbuffers.Offset, team:number, playerId:number):flatbuffers.Offset {
  PlayerConfiguration.startPlayerConfiguration(builder);
  PlayerConfiguration.addVarietyType(builder, varietyType);
  PlayerConfiguration.addVariety(builder, varietyOffset);
  PlayerConfiguration.addTeam(builder, team);
  PlayerConfiguration.addPlayerId(builder, playerId);
  return PlayerConfiguration.endPlayerConfiguration(builder);
}

unpack(): PlayerConfigurationT {
  return new PlayerConfigurationT(
    this.varietyType(),
    (() => {
      const temp = unionToPlayerClass(this.varietyType(), this.variety.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })(),
    this.team(),
    this.playerId()
  );
}


unpackTo(_o: PlayerConfigurationT): void {
  _o.varietyType = this.varietyType();
  _o.variety = (() => {
      const temp = unionToPlayerClass(this.varietyType(), this.variety.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
  _o.team = this.team();
  _o.playerId = this.playerId();
}
}

export class PlayerConfigurationT implements flatbuffers.IGeneratedObject {
constructor(
  public varietyType: PlayerClass = PlayerClass.NONE,
  public variety: CustomBotT|HumanT|PsyonixBotT|null = null,
  public team: number = 0,
  public playerId: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const variety = builder.createObjectOffset(this.variety);

  return PlayerConfiguration.createPlayerConfiguration(builder,
    this.varietyType,
    variety,
    this.team,
    this.playerId
  );
}
}
