// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CustomBot, CustomBotT } from '../../flat/flat/custom-bot.js';
import { Human, HumanT } from '../../flat/flat/human.js';
import { PsyonixBot, PsyonixBotT } from '../../flat/flat/psyonix-bot.js';


/**
 * Possible player types.
 */
export enum PlayerClass {
  NONE = 0,
  Human = 1,
  CustomBot = 2,
  PsyonixBot = 3
}

export function unionToPlayerClass(
  type: PlayerClass,
  accessor: (obj:CustomBot|Human|PsyonixBot) => CustomBot|Human|PsyonixBot|null
): CustomBot|Human|PsyonixBot|null {
  switch(PlayerClass[type]) {
    case 'NONE': return null; 
    case 'Human': return accessor(new Human())! as Human;
    case 'CustomBot': return accessor(new CustomBot())! as CustomBot;
    case 'PsyonixBot': return accessor(new PsyonixBot())! as PsyonixBot;
    default: return null;
  }
}

export function unionListToPlayerClass(
  type: PlayerClass, 
  accessor: (index: number, obj:CustomBot|Human|PsyonixBot) => CustomBot|Human|PsyonixBot|null, 
  index: number
): CustomBot|Human|PsyonixBot|null {
  switch(PlayerClass[type]) {
    case 'NONE': return null; 
    case 'Human': return accessor(index, new Human())! as Human;
    case 'CustomBot': return accessor(index, new CustomBot())! as CustomBot;
    case 'PsyonixBot': return accessor(index, new PsyonixBot())! as PsyonixBot;
    default: return null;
  }
}
