// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { Vector3, Vector3T } from '../../flat/flat/vector3.js';


/**
 * A RenderMessage for a line in 3D space going through a series of points.
 */
export class PolyLine3D implements flatbuffers.IUnpackableObject<PolyLine3DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PolyLine3D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPolyLine3D(bb:flatbuffers.ByteBuffer, obj?:PolyLine3D):PolyLine3D {
  return (obj || new PolyLine3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPolyLine3D(bb:flatbuffers.ByteBuffer, obj?:PolyLine3D):PolyLine3D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PolyLine3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

points(index: number, obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vector3()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
}

pointsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startPolyLine3D(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPoints(builder:flatbuffers.Builder, pointsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pointsOffset, 0);
}

static startPointsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, colorOffset, 0);
}

static endPolyLine3D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // points
  builder.requiredField(offset, 6) // color
  return offset;
}


unpack(): PolyLine3DT {
  return new PolyLine3DT(
    this.bb!.createObjList<Vector3, Vector3T>(this.points.bind(this), this.pointsLength()),
    (this.color() !== null ? this.color()!.unpack() : null)
  );
}


unpackTo(_o: PolyLine3DT): void {
  _o.points = this.bb!.createObjList<Vector3, Vector3T>(this.points.bind(this), this.pointsLength());
  _o.color = (this.color() !== null ? this.color()!.unpack() : null);
}
}

export class PolyLine3DT implements flatbuffers.IGeneratedObject {
constructor(
  public points: (Vector3T)[] = [],
  public color: ColorT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const points = builder.createStructOffsetList(this.points, PolyLine3D.startPointsVector);

  PolyLine3D.startPolyLine3D(builder);
  PolyLine3D.addPoints(builder, points);
  PolyLine3D.addColor(builder, (this.color !== null ? this.color!.pack(builder) : 0));

  return PolyLine3D.endPolyLine3D(builder);
}
}
