// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerLoadout, PlayerLoadoutT } from '../../flat/flat/player-loadout.js';
import { PsyonixSkill } from '../../flat/flat/psyonix-skill.js';


/**
 * A Psyonix bot, e.g. All Star bot.
 */
export class PsyonixBot implements flatbuffers.IUnpackableObject<PsyonixBotT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PsyonixBot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPsyonixBot(bb:flatbuffers.ByteBuffer, obj?:PsyonixBot):PsyonixBot {
  return (obj || new PsyonixBot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPsyonixBot(bb:flatbuffers.ByteBuffer, obj?:PsyonixBot):PsyonixBot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PsyonixBot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Requested bot name. When match start, RLBot will ensure each bot has a unique name; bots with
 * duplicate names will be renamed with a suffix like `(2)`. For psyonix bots, a blank name will
 * be replaced with one of the official names.
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The loadout of the player.
 */
loadout(obj?:PlayerLoadout):PlayerLoadout|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlayerLoadout()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

botSkill():PsyonixSkill {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PsyonixSkill.Beginner;
}

static startPsyonixBot(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addLoadout(builder:flatbuffers.Builder, loadoutOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, loadoutOffset, 0);
}

static addBotSkill(builder:flatbuffers.Builder, botSkill:PsyonixSkill) {
  builder.addFieldInt8(2, botSkill, PsyonixSkill.Beginner);
}

static endPsyonixBot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  return offset;
}


unpack(): PsyonixBotT {
  return new PsyonixBotT(
    this.name(),
    (this.loadout() !== null ? this.loadout()!.unpack() : null),
    this.botSkill()
  );
}


unpackTo(_o: PsyonixBotT): void {
  _o.name = this.name();
  _o.loadout = (this.loadout() !== null ? this.loadout()!.unpack() : null);
  _o.botSkill = this.botSkill();
}
}

export class PsyonixBotT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public loadout: PlayerLoadoutT|null = null,
  public botSkill: PsyonixSkill = PsyonixSkill.Beginner
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const loadout = (this.loadout !== null ? this.loadout!.pack(builder) : 0);

  PsyonixBot.startPsyonixBot(builder);
  PsyonixBot.addName(builder, name);
  PsyonixBot.addLoadout(builder, loadout);
  PsyonixBot.addBotSkill(builder, this.botSkill);

  return PsyonixBot.endPsyonixBot(builder);
}
}
