// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Various skill levels of Psyonix bots.
 */
export enum PsyonixSkill {
  Beginner = 0,
  Rookie = 1,
  Pro = 2,
  AllStar = 3
}
