// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { RenderAnchor, RenderAnchorT } from '../../flat/flat/render-anchor.js';
import { TextHAlign } from '../../flat/flat/text-halign.js';
import { TextVAlign } from '../../flat/flat/text-valign.js';


/**
 * A RenderMessage for a rectangle in 3D space.
 * Note that the size is given in screen-space sizes.
 */
export class Rect3D implements flatbuffers.IUnpackableObject<Rect3DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Rect3D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRect3D(bb:flatbuffers.ByteBuffer, obj?:Rect3D):Rect3D {
  return (obj || new Rect3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRect3D(bb:flatbuffers.ByteBuffer, obj?:Rect3D):Rect3D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Rect3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The position of the rectangle.
 */
anchor(obj?:RenderAnchor):RenderAnchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new RenderAnchor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * Screen-space size such that width=0.1 is 10% of window width.
 */
width():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Screen-space size such that height=0.1 is 10% of window height.
 */
height():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * The color of the rectangle.
 */
color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The horizontal alignment of the anchor in the rectangle.
 */
hAlign():TextHAlign {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextHAlign.Left;
}

/**
 * The vertical alignment of the anchor in the rectangle.
 */
vAlign():TextVAlign {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextVAlign.Top;
}

static startRect3D(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addAnchor(builder:flatbuffers.Builder, anchorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, anchorOffset, 0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(1, width, 0.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(2, height, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, colorOffset, 0);
}

static addHAlign(builder:flatbuffers.Builder, hAlign:TextHAlign) {
  builder.addFieldInt8(4, hAlign, TextHAlign.Left);
}

static addVAlign(builder:flatbuffers.Builder, vAlign:TextVAlign) {
  builder.addFieldInt8(5, vAlign, TextVAlign.Top);
}

static endRect3D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // anchor
  builder.requiredField(offset, 10) // color
  return offset;
}


unpack(): Rect3DT {
  return new Rect3DT(
    (this.anchor() !== null ? this.anchor()!.unpack() : null),
    this.width(),
    this.height(),
    (this.color() !== null ? this.color()!.unpack() : null),
    this.hAlign(),
    this.vAlign()
  );
}


unpackTo(_o: Rect3DT): void {
  _o.anchor = (this.anchor() !== null ? this.anchor()!.unpack() : null);
  _o.width = this.width();
  _o.height = this.height();
  _o.color = (this.color() !== null ? this.color()!.unpack() : null);
  _o.hAlign = this.hAlign();
  _o.vAlign = this.vAlign();
}
}

export class Rect3DT implements flatbuffers.IGeneratedObject {
constructor(
  public anchor: RenderAnchorT|null = null,
  public width: number = 0.0,
  public height: number = 0.0,
  public color: ColorT|null = null,
  public hAlign: TextHAlign = TextHAlign.Left,
  public vAlign: TextVAlign = TextVAlign.Top
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const anchor = (this.anchor !== null ? this.anchor!.pack(builder) : 0);

  Rect3D.startRect3D(builder);
  Rect3D.addAnchor(builder, anchor);
  Rect3D.addWidth(builder, this.width);
  Rect3D.addHeight(builder, this.height);
  Rect3D.addColor(builder, (this.color !== null ? this.color!.pack(builder) : 0));
  Rect3D.addHAlign(builder, this.hAlign);
  Rect3D.addVAlign(builder, this.vAlign);

  return Rect3D.endRect3D(builder);
}
}
