// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { TextHAlign } from '../../flat/flat/text-halign.js';
import { TextVAlign } from '../../flat/flat/text-valign.js';


/**
 * A RenderMessage for a rectangle in 2D space.
 * Note that the position and size is given in screen-space coordinates.
 */
export class Rect2D implements flatbuffers.IUnpackableObject<Rect2DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Rect2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRect2D(bb:flatbuffers.ByteBuffer, obj?:Rect2D):Rect2D {
  return (obj || new Rect2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRect2D(bb:flatbuffers.ByteBuffer, obj?:Rect2D):Rect2D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Rect2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Screen-space x coordinate such that x=0 is left edge and x=1 is right edge of window.
 */
x():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Screen-space y coordinate such that y=0 is top edge and y=1 is bottom edge of window.
 */
y():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Screen-space size such that width=0.1 is 10% of window width.
 */
width():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Screen-space size such that height=0.1 is 10% of window height.
 */
height():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Color of the rectangle.
 */
color(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The horizontal alignment of the rectangle.
 */
hAlign():TextHAlign {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextHAlign.Left;
}

/**
 * The vertical alignment of the rectangle.
 */
vAlign():TextVAlign {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextVAlign.Top;
}

static startRect2D(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(0, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(1, y, 0.0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldFloat32(2, width, 0.0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldFloat32(3, height, 0.0);
}

static addColor(builder:flatbuffers.Builder, colorOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, colorOffset, 0);
}

static addHAlign(builder:flatbuffers.Builder, hAlign:TextHAlign) {
  builder.addFieldInt8(5, hAlign, TextHAlign.Left);
}

static addVAlign(builder:flatbuffers.Builder, vAlign:TextVAlign) {
  builder.addFieldInt8(6, vAlign, TextVAlign.Top);
}

static endRect2D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 12) // color
  return offset;
}


unpack(): Rect2DT {
  return new Rect2DT(
    this.x(),
    this.y(),
    this.width(),
    this.height(),
    (this.color() !== null ? this.color()!.unpack() : null),
    this.hAlign(),
    this.vAlign()
  );
}


unpackTo(_o: Rect2DT): void {
  _o.x = this.x();
  _o.y = this.y();
  _o.width = this.width();
  _o.height = this.height();
  _o.color = (this.color() !== null ? this.color()!.unpack() : null);
  _o.hAlign = this.hAlign();
  _o.vAlign = this.vAlign();
}
}

export class Rect2DT implements flatbuffers.IGeneratedObject {
constructor(
  public x: number = 0.0,
  public y: number = 0.0,
  public width: number = 0.0,
  public height: number = 0.0,
  public color: ColorT|null = null,
  public hAlign: TextHAlign = TextHAlign.Left,
  public vAlign: TextVAlign = TextVAlign.Top
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  Rect2D.startRect2D(builder);
  Rect2D.addX(builder, this.x);
  Rect2D.addY(builder, this.y);
  Rect2D.addWidth(builder, this.width);
  Rect2D.addHeight(builder, this.height);
  Rect2D.addColor(builder, (this.color !== null ? this.color!.pack(builder) : 0));
  Rect2D.addHAlign(builder, this.hAlign);
  Rect2D.addVAlign(builder, this.vAlign);

  return Rect2D.endRect2D(builder);
}
}
