// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BallAnchor, BallAnchorT } from '../../flat/flat/ball-anchor.js';
import { CarAnchor, CarAnchorT } from '../../flat/flat/car-anchor.js';


/**
 * Anchors attached to objects.
 */
export enum RelativeAnchor {
  NONE = 0,
  BallAnchor = 1,
  CarAnchor = 2
}

export function unionToRelativeAnchor(
  type: RelativeAnchor,
  accessor: (obj:BallAnchor|CarAnchor) => BallAnchor|CarAnchor|null
): BallAnchor|CarAnchor|null {
  switch(RelativeAnchor[type]) {
    case 'NONE': return null; 
    case 'BallAnchor': return accessor(new BallAnchor())! as BallAnchor;
    case 'CarAnchor': return accessor(new CarAnchor())! as CarAnchor;
    default: return null;
  }
}

export function unionListToRelativeAnchor(
  type: RelativeAnchor, 
  accessor: (index: number, obj:BallAnchor|CarAnchor) => BallAnchor|CarAnchor|null, 
  index: number
): BallAnchor|CarAnchor|null {
  switch(RelativeAnchor[type]) {
    case 'NONE': return null; 
    case 'BallAnchor': return accessor(index, new BallAnchor())! as BallAnchor;
    case 'CarAnchor': return accessor(index, new CarAnchor())! as CarAnchor;
    default: return null;
  }
}
