// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A client message request removal of a RenderGroup.
 * A client can only clear its own RenderGroups.
 */
export class RemoveRenderGroup implements flatbuffers.IUnpackableObject<RemoveRenderGroupT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveRenderGroup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveRenderGroup(bb:flatbuffers.ByteBuffer, obj?:RemoveRenderGroup):RemoveRenderGroup {
  return (obj || new RemoveRenderGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveRenderGroup(bb:flatbuffers.ByteBuffer, obj?:RemoveRenderGroup):RemoveRenderGroup {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveRenderGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startRemoveRenderGroup(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static endRemoveRenderGroup(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRemoveRenderGroup(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  RemoveRenderGroup.startRemoveRenderGroup(builder);
  RemoveRenderGroup.addId(builder, id);
  return RemoveRenderGroup.endRemoveRenderGroup(builder);
}

unpack(): RemoveRenderGroupT {
  return new RemoveRenderGroupT(
    this.id()
  );
}


unpackTo(_o: RemoveRenderGroupT): void {
  _o.id = this.id();
}
}

export class RemoveRenderGroupT implements flatbuffers.IGeneratedObject {
constructor(
  public id: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RemoveRenderGroup.createRemoveRenderGroup(builder,
    this.id
  );
}
}
