// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Line3D, Line3DT } from '../../flat/flat/line3-d.js';
import { PolyLine3D, PolyLine3DT } from '../../flat/flat/poly-line3-d.js';
import { Rect2D, Rect2DT } from '../../flat/flat/rect2-d.js';
import { Rect3D, Rect3DT } from '../../flat/flat/rect3-d.js';
import { RenderType, unionToRenderType, unionListToRenderType } from '../../flat/flat/render-type.js';
import { String2D, String2DT } from '../../flat/flat/string2-d.js';
import { String3D, String3DT } from '../../flat/flat/string3-d.js';


/**
 * A RenderMessage, describing a piece of debug rendering.
 */
export class RenderMessage implements flatbuffers.IUnpackableObject<RenderMessageT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RenderMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRenderMessage(bb:flatbuffers.ByteBuffer, obj?:RenderMessage):RenderMessage {
  return (obj || new RenderMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRenderMessage(bb:flatbuffers.ByteBuffer, obj?:RenderMessage):RenderMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RenderMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

varietyType():RenderType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RenderType.NONE;
}

variety<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startRenderMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addVarietyType(builder:flatbuffers.Builder, varietyType:RenderType) {
  builder.addFieldInt8(0, varietyType, RenderType.NONE);
}

static addVariety(builder:flatbuffers.Builder, varietyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, varietyOffset, 0);
}

static endRenderMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // variety
  return offset;
}

static createRenderMessage(builder:flatbuffers.Builder, varietyType:RenderType, varietyOffset:flatbuffers.Offset):flatbuffers.Offset {
  RenderMessage.startRenderMessage(builder);
  RenderMessage.addVarietyType(builder, varietyType);
  RenderMessage.addVariety(builder, varietyOffset);
  return RenderMessage.endRenderMessage(builder);
}

unpack(): RenderMessageT {
  return new RenderMessageT(
    this.varietyType(),
    (() => {
      const temp = unionToRenderType(this.varietyType(), this.variety.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: RenderMessageT): void {
  _o.varietyType = this.varietyType();
  _o.variety = (() => {
      const temp = unionToRenderType(this.varietyType(), this.variety.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class RenderMessageT implements flatbuffers.IGeneratedObject {
constructor(
  public varietyType: RenderType = RenderType.NONE,
  public variety: Line3DT|PolyLine3DT|Rect2DT|Rect3DT|String2DT|String3DT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const variety = builder.createObjectOffset(this.variety);

  return RenderMessage.createRenderMessage(builder,
    this.varietyType,
    variety
  );
}
}
