// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * As an interface message, this requests for a specificed agent to have its ability to render changed.
 * This changed will then be broadcasted to all current connections as a core message.
 * Does nothing if rendering has been completely disabled.
 */
export class RenderingStatus implements flatbuffers.IUnpackableObject<RenderingStatusT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RenderingStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRenderingStatus(bb:flatbuffers.ByteBuffer, obj?:RenderingStatus):RenderingStatus {
  return (obj || new RenderingStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRenderingStatus(bb:flatbuffers.ByteBuffer, obj?:RenderingStatus):RenderingStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RenderingStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * If `is_bot`, this is the index of the bot in `GamePacket` that has been updated.
 * Otherwise, this is the index of the script in `MatchConfiguration` that has been updated.
 */
index():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Identifies if the index is that of a bot or a script
 */
isBot():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * If rendering is now enabled or disabled for the specific agent
 */
status():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startRenderingStatus(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
}

static addIsBot(builder:flatbuffers.Builder, isBot:boolean) {
  builder.addFieldInt8(1, +isBot, +false);
}

static addStatus(builder:flatbuffers.Builder, status:boolean) {
  builder.addFieldInt8(2, +status, +false);
}

static endRenderingStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRenderingStatus(builder:flatbuffers.Builder, index:number, isBot:boolean, status:boolean):flatbuffers.Offset {
  RenderingStatus.startRenderingStatus(builder);
  RenderingStatus.addIndex(builder, index);
  RenderingStatus.addIsBot(builder, isBot);
  RenderingStatus.addStatus(builder, status);
  return RenderingStatus.endRenderingStatus(builder);
}

unpack(): RenderingStatusT {
  return new RenderingStatusT(
    this.index(),
    this.isBot(),
    this.status()
  );
}


unpackTo(_o: RenderingStatusT): void {
  _o.index = this.index();
  _o.isBot = this.isBot();
  _o.status = this.status();
}
}

export class RenderingStatusT implements flatbuffers.IGeneratedObject {
constructor(
  public index: number = 0,
  public isBot: boolean = false,
  public status: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RenderingStatus.createRenderingStatus(builder,
    this.index,
    this.isBot,
    this.status
  );
}
}
