// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Line3D, Line3DT } from '../../flat/flat/line3-d.js';
import { PolyLine3D, PolyLine3DT } from '../../flat/flat/poly-line3-d.js';
import { Rect2D, Rect2DT } from '../../flat/flat/rect2-d.js';
import { Rect3D, Rect3DT } from '../../flat/flat/rect3-d.js';
import { String2D, String2DT } from '../../flat/flat/string2-d.js';
import { String3D, String3DT } from '../../flat/flat/string3-d.js';


/**
 * The different types of RenderMessages.
 */
export enum RenderType {
  NONE = 0,
  Line3D = 1,
  PolyLine3D = 2,
  String2D = 3,
  String3D = 4,
  Rect2D = 5,
  Rect3D = 6
}

export function unionToRenderType(
  type: RenderType,
  accessor: (obj:Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D) => Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D|null
): Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D|null {
  switch(RenderType[type]) {
    case 'NONE': return null; 
    case 'Line3D': return accessor(new Line3D())! as Line3D;
    case 'PolyLine3D': return accessor(new PolyLine3D())! as PolyLine3D;
    case 'String2D': return accessor(new String2D())! as String2D;
    case 'String3D': return accessor(new String3D())! as String3D;
    case 'Rect2D': return accessor(new Rect2D())! as Rect2D;
    case 'Rect3D': return accessor(new Rect3D())! as Rect3D;
    default: return null;
  }
}

export function unionListToRenderType(
  type: RenderType, 
  accessor: (index: number, obj:Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D) => Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D|null, 
  index: number
): Line3D|PolyLine3D|Rect2D|Rect3D|String2D|String3D|null {
  switch(RenderType[type]) {
    case 'NONE': return null; 
    case 'Line3D': return accessor(index, new Line3D())! as Line3D;
    case 'PolyLine3D': return accessor(index, new PolyLine3D())! as PolyLine3D;
    case 'String2D': return accessor(index, new String2D())! as String2D;
    case 'String3D': return accessor(index, new String3D())! as String3D;
    case 'Rect2D': return accessor(index, new Rect2D())! as Rect2D;
    case 'Rect3D': return accessor(index, new Rect3D())! as Rect3D;
    default: return null;
  }
}
