// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BallAnchor, BallAnchorT } from '../../flat/flat/ball-anchor.js';
import { CarAnchor, CarAnchorT } from '../../flat/flat/car-anchor.js';
import { RelativeAnchor, unionToRelativeAnchor, unionListToRelativeAnchor } from '../../flat/flat/relative-anchor.js';
import { Vector3, Vector3T } from '../../flat/flat/vector3.js';


/**
 * A RenderAnchor is a point in space consisting of a world component and optionally a relative component.
 * The relative component is given by a car or ball and includes a local offset that takes the orientation of the object into account.
 * The RenderAnchor stays attached to the object and does not have to be updated each tick.
 * Rendering that uses a RenderAnchor attached to an object disappears if the object is destroyed, i.e. the car demolished or the ball is scored.
 */
export class RenderAnchor implements flatbuffers.IUnpackableObject<RenderAnchorT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RenderAnchor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRenderAnchor(bb:flatbuffers.ByteBuffer, obj?:RenderAnchor):RenderAnchor {
  return (obj || new RenderAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRenderAnchor(bb:flatbuffers.ByteBuffer, obj?:RenderAnchor):RenderAnchor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RenderAnchor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * An offset in global coordinates.
 * If the relative component is null, then this simply a point in 3D space.
 */
world(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

relativeType():RelativeAnchor {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RelativeAnchor.NONE;
}

/**
 * An optional offset given by the position of an object and includes a local offset that takes the object's orientation into account.
 */
relative<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startRenderAnchor(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addWorld(builder:flatbuffers.Builder, worldOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, worldOffset, 0);
}

static addRelativeType(builder:flatbuffers.Builder, relativeType:RelativeAnchor) {
  builder.addFieldInt8(1, relativeType, RelativeAnchor.NONE);
}

static addRelative(builder:flatbuffers.Builder, relativeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, relativeOffset, 0);
}

static endRenderAnchor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // world
  return offset;
}

static createRenderAnchor(builder:flatbuffers.Builder, worldOffset:flatbuffers.Offset, relativeType:RelativeAnchor, relativeOffset:flatbuffers.Offset):flatbuffers.Offset {
  RenderAnchor.startRenderAnchor(builder);
  RenderAnchor.addWorld(builder, worldOffset);
  RenderAnchor.addRelativeType(builder, relativeType);
  RenderAnchor.addRelative(builder, relativeOffset);
  return RenderAnchor.endRenderAnchor(builder);
}

unpack(): RenderAnchorT {
  return new RenderAnchorT(
    (this.world() !== null ? this.world()!.unpack() : null),
    this.relativeType(),
    (() => {
      const temp = unionToRelativeAnchor(this.relativeType(), this.relative.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: RenderAnchorT): void {
  _o.world = (this.world() !== null ? this.world()!.unpack() : null);
  _o.relativeType = this.relativeType();
  _o.relative = (() => {
      const temp = unionToRelativeAnchor(this.relativeType(), this.relative.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class RenderAnchorT implements flatbuffers.IGeneratedObject {
constructor(
  public world: Vector3T|null = null,
  public relativeType: RelativeAnchor = RelativeAnchor.NONE,
  public relative: BallAnchorT|CarAnchorT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const relative = builder.createObjectOffset(this.relative);

  return RenderAnchor.createRenderAnchor(builder,
    (this.world !== null ? this.world!.pack(builder) : 0),
    this.relativeType,
    relative
  );
}
}
