// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Respawn time mutator options.
 */
export enum RespawnTimeMutator {
  ThreeSeconds = 0,
  TwoSeconds = 1,
  OneSecond = 2,
  DisableGoalReset = 3
}
