// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Rumble mutator options.
 */
export enum RumbleMutator {
  Off = 0,
  DefaultRumble = 1,
  Slow = 2,
  Civilized = 3,
  DestructionDerby = 4,
  SpringLoaded = 5,
  SpikesOnly = 6,
  SpikeRush = 7,
  HauntedBallBeam = 8,
  Tactical = 9,
  BatmanRumble = 10,
  GrapplingOnly = 11,
  HaymakerOnly = 12,
  SpikeRushForce = 13,
  RPS = 14
}
