// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A collection of values shown on the scoreboard (and a few more).
 */
export class ScoreInfo implements flatbuffers.IUnpackableObject<ScoreInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScoreInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * The accumulated score, roughly indicating how well a player performs.
 */
score():number {
  return this.bb!.readUint32(this.bb_pos);
}

/**
 * Number of goals scored.
 */
goals():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

/**
 * Number of own-goals scored.
 */
ownGoals():number {
  return this.bb!.readUint32(this.bb_pos + 8);
}

/**
 * Number of goals assisted.
 */
assists():number {
  return this.bb!.readUint32(this.bb_pos + 12);
}

/**
 * Number of shots saved.
 */
saves():number {
  return this.bb!.readUint32(this.bb_pos + 16);
}

/**
 * Number of shots on opponent goal.
 */
shots():number {
  return this.bb!.readUint32(this.bb_pos + 20);
}

/**
 * Number of demolitions made.
 */
demolitions():number {
  return this.bb!.readUint32(this.bb_pos + 24);
}

static sizeOf():number {
  return 28;
}

static createScoreInfo(builder:flatbuffers.Builder, score: number, goals: number, own_goals: number, assists: number, saves: number, shots: number, demolitions: number):flatbuffers.Offset {
  builder.prep(4, 28);
  builder.writeInt32(demolitions);
  builder.writeInt32(shots);
  builder.writeInt32(saves);
  builder.writeInt32(assists);
  builder.writeInt32(own_goals);
  builder.writeInt32(goals);
  builder.writeInt32(score);
  return builder.offset();
}


unpack(): ScoreInfoT {
  return new ScoreInfoT(
    this.score(),
    this.goals(),
    this.ownGoals(),
    this.assists(),
    this.saves(),
    this.shots(),
    this.demolitions()
  );
}


unpackTo(_o: ScoreInfoT): void {
  _o.score = this.score();
  _o.goals = this.goals();
  _o.ownGoals = this.ownGoals();
  _o.assists = this.assists();
  _o.saves = this.saves();
  _o.shots = this.shots();
  _o.demolitions = this.demolitions();
}
}

export class ScoreInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public score: number = 0,
  public goals: number = 0,
  public ownGoals: number = 0,
  public assists: number = 0,
  public saves: number = 0,
  public shots: number = 0,
  public demolitions: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ScoreInfo.createScoreInfo(builder,
    this.score,
    this.goals,
    this.ownGoals,
    this.assists,
    this.saves,
    this.shots,
    this.demolitions
  );
}
}
