// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A ScriptConfiguration defines a script of a match.
 */
export class ScriptConfiguration implements flatbuffers.IUnpackableObject<ScriptConfigurationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScriptConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScriptConfiguration(bb:flatbuffers.ByteBuffer, obj?:ScriptConfiguration):ScriptConfiguration {
  return (obj || new ScriptConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScriptConfiguration(bb:flatbuffers.ByteBuffer, obj?:ScriptConfiguration):ScriptConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScriptConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The name of the script.
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The root directory of the script and the working directory for the run command.
 */
rootDir():string|null
rootDir(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rootDir(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * A console command that will start up the script.
 */
runCommand():string|null
runCommand(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
runCommand(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The id of the script.
 * This value is mostly used internally to keep track of participants in the match.
 */
scriptId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * A unique user-defined string that is used to connect clients to the right players/scripts.
 * If a bot/script has a run command, RLBot will pass this agent id to the process using an environment variable, RLBOT_AGENT_ID.
 * Upon connecting the process announces that it is responsible for this agent id and RLBot will pair the two.
 * The recommended format for agent ids is "developername/botname".
 */
agentId():string|null
agentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
agentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScriptConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addRootDir(builder:flatbuffers.Builder, rootDirOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rootDirOffset, 0);
}

static addRunCommand(builder:flatbuffers.Builder, runCommandOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, runCommandOffset, 0);
}

static addScriptId(builder:flatbuffers.Builder, scriptId:number) {
  builder.addFieldInt32(3, scriptId, 0);
}

static addAgentId(builder:flatbuffers.Builder, agentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, agentIdOffset, 0);
}

static endScriptConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // name
  builder.requiredField(offset, 6) // root_dir
  builder.requiredField(offset, 8) // run_command
  builder.requiredField(offset, 12) // agent_id
  return offset;
}

static createScriptConfiguration(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, rootDirOffset:flatbuffers.Offset, runCommandOffset:flatbuffers.Offset, scriptId:number, agentIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScriptConfiguration.startScriptConfiguration(builder);
  ScriptConfiguration.addName(builder, nameOffset);
  ScriptConfiguration.addRootDir(builder, rootDirOffset);
  ScriptConfiguration.addRunCommand(builder, runCommandOffset);
  ScriptConfiguration.addScriptId(builder, scriptId);
  ScriptConfiguration.addAgentId(builder, agentIdOffset);
  return ScriptConfiguration.endScriptConfiguration(builder);
}

unpack(): ScriptConfigurationT {
  return new ScriptConfigurationT(
    this.name(),
    this.rootDir(),
    this.runCommand(),
    this.scriptId(),
    this.agentId()
  );
}


unpackTo(_o: ScriptConfigurationT): void {
  _o.name = this.name();
  _o.rootDir = this.rootDir();
  _o.runCommand = this.runCommand();
  _o.scriptId = this.scriptId();
  _o.agentId = this.agentId();
}
}

export class ScriptConfigurationT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public rootDir: string|Uint8Array|null = null,
  public runCommand: string|Uint8Array|null = null,
  public scriptId: number = 0,
  public agentId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const rootDir = (this.rootDir !== null ? builder.createString(this.rootDir!) : 0);
  const runCommand = (this.runCommand !== null ? builder.createString(this.runCommand!) : 0);
  const agentId = (this.agentId !== null ? builder.createString(this.agentId!) : 0);

  return ScriptConfiguration.createScriptConfiguration(builder,
    name,
    rootDir,
    runCommand,
    this.scriptId,
    agentId
  );
}
}
