// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Series length mutator options.
 */
export enum SeriesLengthMutator {
  Unlimited = 0,
  ThreeGames = 1,
  FiveGames = 2,
  SevenGames = 3
}
