// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerLoadout, PlayerLoadoutT } from '../../flat/flat/player-loadout.js';


/**
 * A client message to change the loadout of a car.
 * If sent before the ready message, this simply sets the loadout of the car.
 * If sent after the ready message and if game state setting is enabled, this will respawn the car with the new loadout.
 * Bots can only set the loadout of their own car(s).
 */
export class SetLoadout implements flatbuffers.IUnpackableObject<SetLoadoutT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetLoadout {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetLoadout(bb:flatbuffers.ByteBuffer, obj?:SetLoadout):SetLoadout {
  return (obj || new SetLoadout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetLoadout(bb:flatbuffers.ByteBuffer, obj?:SetLoadout):SetLoadout {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetLoadout()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The index of the car to change loadout off.
 */
index():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The new loadout of the car.
 */
loadout(obj?:PlayerLoadout):PlayerLoadout|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlayerLoadout()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSetLoadout(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
}

static addLoadout(builder:flatbuffers.Builder, loadoutOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, loadoutOffset, 0);
}

static endSetLoadout(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // loadout
  return offset;
}


unpack(): SetLoadoutT {
  return new SetLoadoutT(
    this.index(),
    (this.loadout() !== null ? this.loadout()!.unpack() : null)
  );
}


unpackTo(_o: SetLoadoutT): void {
  _o.index = this.index();
  _o.loadout = (this.loadout() !== null ? this.loadout()!.unpack() : null);
}
}

export class SetLoadoutT implements flatbuffers.IGeneratedObject {
constructor(
  public index: number = 0,
  public loadout: PlayerLoadoutT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const loadout = (this.loadout !== null ? this.loadout!.pack(builder) : 0);

  SetLoadout.startSetLoadout(builder);
  SetLoadout.addIndex(builder, this.index);
  SetLoadout.addLoadout(builder, loadout);

  return SetLoadout.endSetLoadout(builder);
}
}
