// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A client message to start a match using a path to a match config file.
 */
export class StartCommand implements flatbuffers.IUnpackableObject<StartCommandT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartCommand(bb:flatbuffers.ByteBuffer, obj?:StartCommand):StartCommand {
  return (obj || new StartCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartCommand(bb:flatbuffers.ByteBuffer, obj?:StartCommand):StartCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

configPath():string|null
configPath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
configPath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStartCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addConfigPath(builder:flatbuffers.Builder, configPathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, configPathOffset, 0);
}

static endStartCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // config_path
  return offset;
}

static createStartCommand(builder:flatbuffers.Builder, configPathOffset:flatbuffers.Offset):flatbuffers.Offset {
  StartCommand.startStartCommand(builder);
  StartCommand.addConfigPath(builder, configPathOffset);
  return StartCommand.endStartCommand(builder);
}

unpack(): StartCommandT {
  return new StartCommandT(
    this.configPath()
  );
}


unpackTo(_o: StartCommandT): void {
  _o.configPath = this.configPath();
}
}

export class StartCommandT implements flatbuffers.IGeneratedObject {
constructor(
  public configPath: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const configPath = (this.configPath !== null ? builder.createString(this.configPath!) : 0);

  return StartCommand.createStartCommand(builder,
    configPath
  );
}
}
