// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A client message to stop a match and optionally the RLBot server too.
 */
export class StopCommand implements flatbuffers.IUnpackableObject<StopCommandT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StopCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStopCommand(bb:flatbuffers.ByteBuffer, obj?:StopCommand):StopCommand {
  return (obj || new StopCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStopCommand(bb:flatbuffers.ByteBuffer, obj?:StopCommand):StopCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StopCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

shutdownServer():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startStopCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addShutdownServer(builder:flatbuffers.Builder, shutdownServer:boolean) {
  builder.addFieldInt8(0, +shutdownServer, +false);
}

static endStopCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStopCommand(builder:flatbuffers.Builder, shutdownServer:boolean):flatbuffers.Offset {
  StopCommand.startStopCommand(builder);
  StopCommand.addShutdownServer(builder, shutdownServer);
  return StopCommand.endStopCommand(builder);
}

unpack(): StopCommandT {
  return new StopCommandT(
    this.shutdownServer()
  );
}


unpackTo(_o: StopCommandT): void {
  _o.shutdownServer = this.shutdownServer();
}
}

export class StopCommandT implements flatbuffers.IGeneratedObject {
constructor(
  public shutdownServer: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StopCommand.createStopCommand(builder,
    this.shutdownServer
  );
}
}
