// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { TextHAlign } from '../../flat/flat/text-halign.js';
import { TextVAlign } from '../../flat/flat/text-valign.js';


/**
 * A RenderMessage for text in 2D space.
 * Note that the position is given in screen-space coordinates.
 */
export class String2D implements flatbuffers.IUnpackableObject<String2DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):String2D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsString2D(bb:flatbuffers.ByteBuffer, obj?:String2D):String2D {
  return (obj || new String2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsString2D(bb:flatbuffers.ByteBuffer, obj?:String2D):String2D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new String2D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The text to be displayed.
 */
text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Screen-space x coordinate such that x=0 is left edge and x=1 is right edge of window.
 */
x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Screen-space y coordinate such that y=0 is top edge and y=1 is bottom edge of window.
 */
y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Scale of the text.
 * When scale is 1, the characters are 20 pixels tall and 10 pixels wide.
 */
scale():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * The color of the text.
 */
foreground(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The color of the background for the text.
 */
background(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The horizontal alignment of the text.
 */
hAlign():TextHAlign {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextHAlign.Left;
}

/**
 * The vertical alignment of the text.
 */
vAlign():TextVAlign {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextVAlign.Top;
}

static startString2D(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addScale(builder:flatbuffers.Builder, scale:number) {
  builder.addFieldFloat32(3, scale, 0.0);
}

static addForeground(builder:flatbuffers.Builder, foregroundOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, foregroundOffset, 0);
}

static addBackground(builder:flatbuffers.Builder, backgroundOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, backgroundOffset, 0);
}

static addHAlign(builder:flatbuffers.Builder, hAlign:TextHAlign) {
  builder.addFieldInt8(6, hAlign, TextHAlign.Left);
}

static addVAlign(builder:flatbuffers.Builder, vAlign:TextVAlign) {
  builder.addFieldInt8(7, vAlign, TextVAlign.Top);
}

static endString2D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  builder.requiredField(offset, 12) // foreground
  builder.requiredField(offset, 14) // background
  return offset;
}


unpack(): String2DT {
  return new String2DT(
    this.text(),
    this.x(),
    this.y(),
    this.scale(),
    (this.foreground() !== null ? this.foreground()!.unpack() : null),
    (this.background() !== null ? this.background()!.unpack() : null),
    this.hAlign(),
    this.vAlign()
  );
}


unpackTo(_o: String2DT): void {
  _o.text = this.text();
  _o.x = this.x();
  _o.y = this.y();
  _o.scale = this.scale();
  _o.foreground = (this.foreground() !== null ? this.foreground()!.unpack() : null);
  _o.background = (this.background() !== null ? this.background()!.unpack() : null);
  _o.hAlign = this.hAlign();
  _o.vAlign = this.vAlign();
}
}

export class String2DT implements flatbuffers.IGeneratedObject {
constructor(
  public text: string|Uint8Array|null = null,
  public x: number = 0.0,
  public y: number = 0.0,
  public scale: number = 0.0,
  public foreground: ColorT|null = null,
  public background: ColorT|null = null,
  public hAlign: TextHAlign = TextHAlign.Left,
  public vAlign: TextVAlign = TextVAlign.Top
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const text = (this.text !== null ? builder.createString(this.text!) : 0);

  String2D.startString2D(builder);
  String2D.addText(builder, text);
  String2D.addX(builder, this.x);
  String2D.addY(builder, this.y);
  String2D.addScale(builder, this.scale);
  String2D.addForeground(builder, (this.foreground !== null ? this.foreground!.pack(builder) : 0));
  String2D.addBackground(builder, (this.background !== null ? this.background!.pack(builder) : 0));
  String2D.addHAlign(builder, this.hAlign);
  String2D.addVAlign(builder, this.vAlign);

  return String2D.endString2D(builder);
}
}
