// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Color, ColorT } from '../../flat/flat/color.js';
import { RenderAnchor, RenderAnchorT } from '../../flat/flat/render-anchor.js';
import { TextHAlign } from '../../flat/flat/text-halign.js';
import { TextVAlign } from '../../flat/flat/text-valign.js';


/**
 * A RenderMessage for text in 3D space.
 */
export class String3D implements flatbuffers.IUnpackableObject<String3DT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):String3D {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsString3D(bb:flatbuffers.ByteBuffer, obj?:String3D):String3D {
  return (obj || new String3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsString3D(bb:flatbuffers.ByteBuffer, obj?:String3D):String3D {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new String3D()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The text to be displayed.
 */
text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The position of the text.
 */
anchor(obj?:RenderAnchor):RenderAnchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RenderAnchor()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * The scale of the text.
 * When scale is 1, the characters are 20 pixels tall and 10 pixels wide.
 */
scale():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * The color of the text.
 */
foreground(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The color of the background for the text.
 */
background(obj?:Color):Color|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Color()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The horizontal alignment of the text.
 */
hAlign():TextHAlign {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextHAlign.Left;
}

/**
 * The vertical alignment of the text.
 */
vAlign():TextVAlign {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : TextVAlign.Top;
}

static startString3D(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addAnchor(builder:flatbuffers.Builder, anchorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, anchorOffset, 0);
}

static addScale(builder:flatbuffers.Builder, scale:number) {
  builder.addFieldFloat32(2, scale, 0.0);
}

static addForeground(builder:flatbuffers.Builder, foregroundOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, foregroundOffset, 0);
}

static addBackground(builder:flatbuffers.Builder, backgroundOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, backgroundOffset, 0);
}

static addHAlign(builder:flatbuffers.Builder, hAlign:TextHAlign) {
  builder.addFieldInt8(5, hAlign, TextHAlign.Left);
}

static addVAlign(builder:flatbuffers.Builder, vAlign:TextVAlign) {
  builder.addFieldInt8(6, vAlign, TextVAlign.Top);
}

static endString3D(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // text
  builder.requiredField(offset, 6) // anchor
  builder.requiredField(offset, 10) // foreground
  builder.requiredField(offset, 12) // background
  return offset;
}


unpack(): String3DT {
  return new String3DT(
    this.text(),
    (this.anchor() !== null ? this.anchor()!.unpack() : null),
    this.scale(),
    (this.foreground() !== null ? this.foreground()!.unpack() : null),
    (this.background() !== null ? this.background()!.unpack() : null),
    this.hAlign(),
    this.vAlign()
  );
}


unpackTo(_o: String3DT): void {
  _o.text = this.text();
  _o.anchor = (this.anchor() !== null ? this.anchor()!.unpack() : null);
  _o.scale = this.scale();
  _o.foreground = (this.foreground() !== null ? this.foreground()!.unpack() : null);
  _o.background = (this.background() !== null ? this.background()!.unpack() : null);
  _o.hAlign = this.hAlign();
  _o.vAlign = this.vAlign();
}
}

export class String3DT implements flatbuffers.IGeneratedObject {
constructor(
  public text: string|Uint8Array|null = null,
  public anchor: RenderAnchorT|null = null,
  public scale: number = 0.0,
  public foreground: ColorT|null = null,
  public background: ColorT|null = null,
  public hAlign: TextHAlign = TextHAlign.Left,
  public vAlign: TextVAlign = TextVAlign.Top
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const text = (this.text !== null ? builder.createString(this.text!) : 0);
  const anchor = (this.anchor !== null ? this.anchor!.pack(builder) : 0);

  String3D.startString3D(builder);
  String3D.addText(builder, text);
  String3D.addAnchor(builder, anchor);
  String3D.addScale(builder, this.scale);
  String3D.addForeground(builder, (this.foreground !== null ? this.foreground!.pack(builder) : 0));
  String3D.addBackground(builder, (this.background !== null ? this.background!.pack(builder) : 0));
  String3D.addHAlign(builder, this.hAlign);
  String3D.addVAlign(builder, this.vAlign);

  return String3D.endString3D(builder);
}
}
