// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Information about teams. Currently only the number of goals scored.
 */
export class TeamInfo implements flatbuffers.IUnpackableObject<TeamInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TeamInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * The index of the team. Blue is 0, orange is 1.
 */
teamIndex():number {
  return this.bb!.readUint32(this.bb_pos);
}

/**
 * Number of goals scored.
 * Note, this value may be different than the sum of the goals scored by the current players on the team as player may join/leave the game or switch teams.
 * This value is what is shown on the heads-up display.
 */
score():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createTeamInfo(builder:flatbuffers.Builder, team_index: number, score: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(score);
  builder.writeInt32(team_index);
  return builder.offset();
}


unpack(): TeamInfoT {
  return new TeamInfoT(
    this.teamIndex(),
    this.score()
  );
}


unpackTo(_o: TeamInfoT): void {
  _o.teamIndex = this.teamIndex();
  _o.score = this.score();
}
}

export class TeamInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public teamIndex: number = 0,
  public score: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return TeamInfo.createTeamInfo(builder,
    this.teamIndex,
    this.score
  );
}
}
