// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Horizontal text alignment.
 */
export enum TextHAlign {
  Left = 0,
  Center = 1,
  Right = 2
}
