// @ts-nocheck automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Vertical text alignment.
 */
export enum TextVAlign {
  Top = 0,
  Center = 1,
  Bottom = 2
}
